//A partir da escolha do estado, a drop down list aparece com os municípios correspondentes

function mudaEstado(x){
    //lista de municípios
    let municipios_por_estado = [
        ["mg","Abadia dos Dourados"],	
        ["mg","Abaete"],	
        ["mg","Abre Campo"],	
        ["mg","Acaiaca"],	
        ["mg","Acucena"],	
        ["mg","Agua Boa"],	
        ["mg","Agua Comprida"],	
        ["mg","Aguanil"],	
        ["mg","Aguas Formosas"],	
        ["mg","Aguas Vermelhas"],	
        ["mg","Aimores"],	
        ["mg","Aiuruoca"],	
        ["mg","Alagoa"],	
        ["mg","Albertina"],	
        ["mg","Alem Paraiba"],	
        ["mg","Alfenas"],	
        ["mg","Alfredo Vasconcelos"],	
        ["mg","Almenara"],	
        ["mg","Alpercata"],	
        ["mg","Alpinopolis"],	
        ["mg","Alterosa"],	
        ["mg","Alto Caparao"],	
        ["mg","Alto Jequitiba"],	
        ["mg","Alto Rio Doce"],	
        ["mg","Alvarenga"],	
        ["mg","Alvinopolis"],	
        ["mg","Alvorada de Minas"],	
        ["mg","Amparo do Serra"],	
        ["mg","Andradas"],	
        ["mg","Andrelandia"],	
        ["mg","Angelandia"],	
        ["mg","Antonio Carlos"],	
        ["mg","Antonio Dias"],	
        ["mg","Antonio Prado de Minas"],	
        ["mg","Aracai"],	
        ["mg","Aracitaba"],	
        ["mg","Aracuai"],	
        ["mg","Araguari"],	
        ["mg","Arantina"],	
        ["mg","Araponga"],	
        ["mg","Arapora"],	
        ["mg","Arapua"],	
        ["mg","Araujos"],	
        ["mg","Araxa"],	
        ["mg","Arceburgo"],	
        ["mg","Arcos"],	
        ["mg","Areado"],	
        ["mg","Argirita"],	
        ["mg","Aricanduva"],	
        ["mg","Arinos"],	
        ["mg","Astolfo Dutra"],	
        ["mg","Ataleia"],	
        ["mg","Augusto de Lima"],	
        ["mg","Baependi"],	
        ["mg","Baldim"],	
        ["mg","Bambui"],	
        ["mg","Bandeira do Sul"],	
        ["mg","Bandeira"],	
        ["mg","Barao de Cocais"],	
        ["mg","Barao de Monte Alto"],	
        ["mg","Barbacena"],	
        ["mg","Barra Longa"],	
        ["mg","Barroso"],	
        ["mg","Bela Vista de Minas"],	
        ["mg","Belmiro Braga"],	
        ["mg","Belo Horizonte"],	
        ["mg","Belo Oriente"],	
        ["mg","Belo Vale"],	
        ["mg","Berilo"],	
        ["mg","Berizal"],	
        ["mg","Bertopolis"],	
        ["mg","Betim"],	
        ["mg","Bias Fortes"],	
        ["mg","Bicas"],	
        ["mg","Biquinhas"],	
        ["mg","Boa Esperanca"],	
        ["mg","Bocaina de Minas"],	
        ["mg","Bocaiuva"],	
        ["mg","Bom Despacho"],	
        ["mg","Bom Jardim de Minas"],	
        ["mg","Bom Jesus da Penha"],	
        ["mg","Bom Jesus do Amparo"],	
        ["mg","Bom Jesus do Galho"],	
        ["mg","Bom Repouso"],	
        ["mg","Bom Sucesso"],	
        ["mg","Bonfim"],	
        ["mg","Bonfinopolis de Minas"],	
        ["mg","Bonito de Minas"],	
        ["mg","Borda da Mata"],	
        ["mg","Botelhos"],	
        ["mg","Botumirim"],	
        ["mg","Bras Pires"],	
        ["mg","Brasilandia de Minas"],	
        ["mg","Brasilia de Minas"],	
        ["mg","Brasopolis"],	
        ["mg","Braunas"],	
        ["mg","Brumadinho"],	
        ["mg","Bueno Brandao"],	
        ["mg","Buenopolis"],	
        ["mg","Bugre"],	
        ["mg","Buritis"],	
        ["mg","Buritizeiro"],	
        ["mg","Cabeceira Grande"],	
        ["mg","Cabo Verde"],	
        ["mg","Cachoeira Dourada"],	
        ["mg","Cachoeira da Prata"],	
        ["mg","Cachoeira de Minas"],	
        ["mg","Cachoeira de Pajeu"],	
        ["mg","Caetanopolis"],	
        ["mg","Caete"],	
        ["mg","Caiana"],	
        ["mg","Cajuri"],	
        ["mg","Caldas"],	
        ["mg","Camacho"],	
        ["mg","Camanducaia"],	
        ["mg","Cambui"],	
        ["mg","Cambuquira"],	
        ["mg","Campanario"],	
        ["mg","Campanha"],	
        ["mg","Campestre"],	
        ["mg","Campina Verde"],	
        ["mg","Campo Azul"],	
        ["mg","Campo Belo"],	
        ["mg","Campo Florido"],	
        ["mg","Campo do Meio"],	
        ["mg","Campos Altos"],	
        ["mg","Campos Gerais"],	
        ["mg","Cana Verde"],	
        ["mg","Canaa"],	
        ["mg","Canapolis"],	
        ["mg","Candeias"],	
        ["mg","Cantagalo"],	
        ["mg","Caparao"],	
        ["mg","Capela Nova"],	
        ["mg","Capelinha"],	
        ["mg","Capetinga"],	
        ["mg","Capim Branco"],	
        ["mg","Capinopolis"],	
        ["mg","Capitao Andrade"],	
        ["mg","Capitao Eneas"],	
        ["mg","Capitolio"],	
        ["mg","Caputira"],	
        ["mg","Carai"],	
        ["mg","Caranaiba"],	
        ["mg","Carandai"],	
        ["mg","Carangola"],	
        ["mg","Caratinga"],	
        ["mg","Carbonita"],	
        ["mg","Careacu"],	
        ["mg","Carlos Chagas"],	
        ["mg","Carmesia"],	
        ["mg","Carmo da Cachoeira"],	
        ["mg","Carmo da Mata"],	
        ["mg","Carmo de Minas"],	
        ["mg","Carmo do Cajuru"],	
        ["mg","Carmo do Paranaiba"],	
        ["mg","Carmo do Rio Claro"],	
        ["mg","Carmopolis de Minas"],	
        ["mg","Carneirinho"],	
        ["mg","Carrancas"],	
        ["mg","Carvalhopolis"],	
        ["mg","Carvalhos"],	
        ["mg","Casa Grande"],	
        ["mg","Cascalho Rico"],	
        ["mg","Cassia"],	
        ["mg","Cataguases"],	
        ["mg","Catas Altas da Noruega"],	
        ["mg","Catas Altas"],	
        ["mg","Catuji"],	
        ["mg","Catuti"],	
        ["mg","Caxambu"],	
        ["mg","Cedro do Abaete"],	
        ["mg","Central de Minas"],	
        ["mg","Centralina"],	
        ["mg","Chacara"],	
        ["mg","Chale"],	
        ["mg","Chapada Gaucha"],	
        ["mg","Chapada do Norte"],	
        ["mg","Chiador"],	
        ["mg","Cipotanea"],	
        ["mg","Claraval"],	
        ["mg","Claro dos Pocoes"],	
        ["mg","Claudio"],	
        ["mg","Coimbra"],	
        ["mg","Coluna"],	
        ["mg","Comendador Gomes"],	
        ["mg","Comercinho"],	
        ["mg","Conceicao da Aparecida"],	
        ["mg","Conceicao da Barra de Minas"],	
        ["mg","Conceicao das Alagoas"],	
        ["mg","Conceicao das Pedras"],	
        ["mg","Conceicao de Ipanema"],	
        ["mg","Conceicao do Mato Dentro"],	
        ["mg","Conceicao do Para"],	
        ["mg","Conceicao do Rio Verde"],	
        ["mg","Conceicao dos Ouros"],	
        ["mg","Conego Marinho"],	
        ["mg","Confins"],	
        ["mg","Congonhal"],	
        ["mg","Congonhas do Norte"],	
        ["mg","Congonhas"],	
        ["mg","Conquista"],	
        ["mg","Conselheiro Lafaiete"],	
        ["mg","Conselheiro Pena"],	
        ["mg","Consolacao"],	
        ["mg","Contagem"],	
        ["mg","Coqueiral"],	
        ["mg","Coracao de Jesus"],	
        ["mg","Cordisburgo"],	
        ["mg","Cordislandia"],	
        ["mg","Corinto"],	
        ["mg","Coroaci"],	
        ["mg","Coromandel"],	
        ["mg","Coronel Fabriciano"],	
        ["mg","Coronel Murta"],	
        ["mg","Coronel Pacheco"],	
        ["mg","Coronel Xavier Chaves"],	
        ["mg","Corrego Danta"],	
        ["mg","Corrego Fundo"],	
        ["mg","Corrego Novo"],	
        ["mg","Corrego do Bom Jesus"],	
        ["mg","Couto de Magalhaes de Minas"],	
        ["mg","Crisolita"],	
        ["mg","Cristais"],	
        ["mg","Cristalia"],	
        ["mg","Cristiano Otoni"],	
        ["mg","Cristina"],	
        ["mg","Crucilandia"],	
        ["mg","Cruzeiro da Fortaleza"],	
        ["mg","Cruzilia"],	
        ["mg","Cuparaque"],	
        ["mg","Curral de Dentro"],	
        ["mg","Curvelo"],	
        ["mg","Datas"],	
        ["mg","Delfim Moreira"],	
        ["mg","Delfinopolis"],	
        ["mg","Delta"],	
        ["mg","Descoberto"],	
        ["mg","Desterro de Entre Rios"],	
        ["mg","Desterro do Melo"],	
        ["mg","Diamantina"],	
        ["mg","Diogo de Vasconcelos"],	
        ["mg","Dionisio"],	
        ["mg","Divinesia"],	
        ["mg","Divino das Laranjeiras"],	
        ["mg","Divino"],	
        ["mg","Divinolandia de Minas"],	
        ["mg","Divinopolis"],	
        ["mg","Divisa Alegre"],	
        ["mg","Divisa Nova"],	
        ["mg","Divisopolis"],	
        ["mg","Dom Bosco"],	
        ["mg","Dom Cavati"],	
        ["mg","Dom Joaquim"],	
        ["mg","Dom Silverio"],	
        ["mg","Dom Vicoso"],	
        ["mg","Dona Euzebia"],	
        ["mg","Dores de Campos"],	
        ["mg","Dores de Guanhaes"],	
        ["mg","Dores do Indaia"],	
        ["mg","Dores do Turvo"],	
        ["mg","Doresopolis"],	
        ["mg","Douradoquara"],	
        ["mg","Durande"],	
        ["mg","Eloi Mendes"],	
        ["mg","Engenheiro Caldas"],	
        ["mg","Engenheiro Navarro"],	
        ["mg","Entre Folhas"],	
        ["mg","Entre Rios de Minas"],	
        ["mg","Ervalia"],	
        ["mg","Esmeraldas"],	
        ["mg","Espera Feliz"],	
        ["mg","Espinosa"],	
        ["mg","Espirito Santo do Dourado"],	
        ["mg","Estiva"],	
        ["mg","Estrela Dalva"],	
        ["mg","Estrela do Indaia"],	
        ["mg","Estrela do Sul"],	
        ["mg","Eugenopolis"],	
        ["mg","Ewbank da Camara"],	
        ["mg","Extrema"],	
        ["mg","Fama"],	
        ["mg","Faria Lemos"],	
        ["mg","Felicio dos Santos"],	
        ["mg","Felisburgo"],	
        ["mg","Felixlandia"],	
        ["mg","Fernandes Tourinho"],	
        ["mg","Ferros"],	
        ["mg","Fervedouro"],	
        ["mg","Florestal"],	
        ["mg","Formiga"],	
        ["mg","Formoso"],	
        ["mg","Fortaleza de Minas"],	
        ["mg","Fortuna de Minas"],	
        ["mg","Francisco Badaro"],	
        ["mg","Francisco Dumont"],	
        ["mg","Francisco Sa"],	
        ["mg","Franciscopolis"],	
        ["mg","Frei Gaspar"],	
        ["mg","Frei Inocencio"],	
        ["mg","Frei Lagonegro"],	
        ["mg","Fronteira dos Vales"],	
        ["mg","Fronteira"],	
        ["mg","Fruta de Leite"],	
        ["mg","Frutal"],	
        ["mg","Funilandia"],	
        ["mg","Galileia"],	
        ["mg","Gameleiras"],	
        ["mg","Glaucilandia"],	
        ["mg","Goiabeira"],	
        ["mg","Goiana"],	
        ["mg","Goncalves"],	
        ["mg","Gonzaga"],	
        ["mg","Gouvea"],	
        ["mg","Governador Valadares"],	
        ["mg","Grao Mogol"],	
        ["mg","Grupiara"],	
        ["mg","Guanhaes"],	
        ["mg","Guape"],	
        ["mg","Guaraciaba"],	
        ["mg","Guaraciama"],	
        ["mg","Guaranesia"],	
        ["mg","Guarani"],	
        ["mg","Guarara"],	
        ["mg","Guarda-Mor"],	
        ["mg","Guaxupe"],	
        ["mg","Guidoval"],	
        ["mg","Guimarania"],	
        ["mg","Guiricema"],	
        ["mg","Gurinhata"],	
        ["mg","Heliodora"],	
        ["mg","Iapu"],	
        ["mg","Ibertioga"],	
        ["mg","Ibia"],	
        ["mg","Ibiai"],	
        ["mg","Ibiracatu"],	
        ["mg","Ibiraci"],	
        ["mg","Ibirite"],	
        ["mg","Ibitiura de Minas"],	
        ["mg","Ibituruna"],	
        ["mg","Icarai de Minas"],	
        ["mg","Igarape"],	
        ["mg","Igaratinga"],	
        ["mg","Iguatama"],	
        ["mg","Ijaci"],	
        ["mg","Ilicinea"],	
        ["mg","Imbe de Minas"],	
        ["mg","Inconfidentes"],	
        ["mg","Indaiabira"],	
        ["mg","Indianopolis"],	
        ["mg","Ingai"],	
        ["mg","Inhapim"],	
        ["mg","Inhauma"],	
        ["mg","Inimutaba"],	
        ["mg","Ipaba"],	
        ["mg","Ipanema"],	
        ["mg","Ipatinga"],	
        ["mg","Ipiacu"],	
        ["mg","Ipuiuna"],	
        ["mg","Irai de Minas"],	
        ["mg","Itabira"],	
        ["mg","Itabirinha de Mantena"],	
        ["mg","Itabirito"],	
        ["mg","Itacambira"],	
        ["mg","Itacarambi"],	
        ["mg","Itaguara"],	
        ["mg","Itaipe"],	
        ["mg","Itajuba"],	
        ["mg","Itamarandiba"],	
        ["mg","Itamarati de Minas"],	
        ["mg","Itambacuri"],	
        ["mg","Itambe do Mato Dentro"],	
        ["mg","Itamogi"],	
        ["mg","Itamonte"],	
        ["mg","Itanhandu"],	
        ["mg","Itanhomi"],	
        ["mg","Itaobim"],	
        ["mg","Itapagipe"],	
        ["mg","Itapecerica"],	
        ["mg","Itapeva"],	
        ["mg","Itatiaiucu"],	
        ["mg","Itau de Minas"],	
        ["mg","Itauna"],	
        ["mg","Itaverava"],	
        ["mg","Itinga"],	
        ["mg","Itueta"],	
        ["mg","Ituiutaba"],	
        ["mg","Itumirim"],	
        ["mg","Iturama"],	
        ["mg","Itutinga"],	
        ["mg","Jaboticatubas"],	
        ["mg","Jacinto"],	
        ["mg","Jacui"],	
        ["mg","Jacutinga"],	
        ["mg","Jaguaracu"],	
        ["mg","Jaiba"],	
        ["mg","Jampruca"],	
        ["mg","Janauba"],	
        ["mg","Januaria"],	
        ["mg","Japaraiba"],	
        ["mg","Japonvar"],	
        ["mg","Jeceaba"],	
        ["mg","Jenipapo de Minas"],	
        ["mg","Jequeri"],	
        ["mg","Jequitai"],	
        ["mg","Jequitiba"],	
        ["mg","Jequitinhonha"],	
        ["mg","Jesuania"],	
        ["mg","Joaima"],	
        ["mg","Joanesia"],	
        ["mg","Joao Monlevade"],	
        ["mg","Joao Pinheiro"],	
        ["mg","Joaquim Felicio"],	
        ["mg","Jordania"],	
        ["mg","Jose Goncalves de Minas"],	
        ["mg","Jose Raydan"],	
        ["mg","Josenopolis"],	
        ["mg","Juatuba"],	
        ["mg","Juiz de Fora"],	
        ["mg","Juramento"],	
        ["mg","Juruaia"],	
        ["mg","Juvenilia"],	
        ["mg","Ladainha"],	
        ["mg","Lagamar"],	
        ["mg","Lagoa Dourada"],	
        ["mg","Lagoa Formosa"],	
        ["mg","Lagoa Grande"],	
        ["mg","Lagoa Santa"],	
        ["mg","Lagoa da Prata"],	
        ["mg","Lagoa dos Patos"],	
        ["mg","Lagoas"],	
        ["mg","Lajinha"],	
        ["mg","Lambari"],	
        ["mg","Lamim"],	
        ["mg","Laranjal"],	
        ["mg","Lassance"],	
        ["mg","Lavras"],	
        ["mg","Leandro Ferreira"],	
        ["mg","Leme do Prado"],	
        ["mg","Leopoldina"],	
        ["mg","Liberdade"],	
        ["mg","Lima Duarte"],	
        ["mg","Limeira do Oeste"],	
        ["mg","Lontra"],	
        ["mg","Luisburgo"],	
        ["mg","Luislandia"],	
        ["mg","Luminarias"],	
        ["mg","Luz"],	
        ["mg","Machacalis"],	
        ["mg","Machado"],	
        ["mg","Madre de Deus de Minas"],	
        ["mg","Malacacheta"],	
        ["mg","Mamonas"],	
        ["mg","Manga"],	
        ["mg","Manhuacu"],	
        ["mg","Manhumirim"],	
        ["mg","Mantena"],	
        ["mg","Mar de Espanha"],	
        ["mg","Maravilhas"],	
        ["mg","Maria da Fe"],	
        ["mg","Mariana"],	
        ["mg","Marilac"],	
        ["mg","Mario Campos"],	
        ["mg","Maripa de Minas"],	
        ["mg","Marlieria"],	
        ["mg","Marmelopolis"],	
        ["mg","Martinho Campos"],	
        ["mg","Martins Soares"],	
        ["mg","Mata Verde"],	
        ["mg","Materlandia"],	
        ["mg","Mateus Leme"],	
        ["mg","Mathias Lobato"],	
        ["mg","Matias Barbosa"],	
        ["mg","Matias Cardoso"],	
        ["mg","Matipo"],	
        ["mg","Mato Verde"],	
        ["mg","Matozinhos"],	
        ["mg","Matutina"],	
        ["mg","Medeiros"],	
        ["mg","Medina"],	
        ["mg","Mendes Pimentel"],	
        ["mg","Merces"],	
        ["mg","Mesquita"],	
        ["mg","Minas Novas"],	
        ["mg","Minduri"],	
        ["mg","Mirabela"],	
        ["mg","Miradouro"],	
        ["mg","Mirai"],	
        ["mg","Miravania"],	
        ["mg","Moeda"],	
        ["mg","Moema"],	
        ["mg","Monjolos"],	
        ["mg","Monsenhor Paulo"],	
        ["mg","Montalvania"],	
        ["mg","Monte Alegre de Minas"],	
        ["mg","Monte Azul"],	
        ["mg","Monte Belo"],	
        ["mg","Monte Carmelo"],	
        ["mg","Monte Formoso"],	
        ["mg","Monte Santo de Minas"],	
        ["mg","Monte Siao"],	
        ["mg","Montes Claros"],	
        ["mg","Montezuma"],	
        ["mg","Morada Nova de Minas"],	
        ["mg","Morro da Garca"],	
        ["mg","Morro do Pilar"],	
        ["mg","Munhoz"],	
        ["mg","Muriae"],	
        ["mg","Mutum"],	
        ["mg","Muzambinho"],	
        ["mg","Nacip Raydan"],	
        ["mg","Nanuque"],	
        ["mg","Naque"],	
        ["mg","Natalandia"],	
        ["mg","Natercia"],	
        ["mg","Nazareno"],	
        ["mg","Nepomuceno"],	
        ["mg","Ninheira"],	
        ["mg","Nova Belem"],	
        ["mg","Nova Era"],	
        ["mg","Nova Lima"],	
        ["mg","Nova Modica"],	
        ["mg","Nova Ponte"],	
        ["mg","Nova Porteirinha"],	
        ["mg","Nova Resende"],	
        ["mg","Nova Serrana"],	
        ["mg","Nova Uniao"],	
        ["mg","Novo Cruzeiro"],	
        ["mg","Novo Oriente de Minas"],	
        ["mg","Novorizonte"],	
        ["mg","Olaria"],	
        ["mg","Olhos-d'Agua"],	
        ["mg","Olimpio Noronha"],	
        ["mg","Oliveira Fortes"],	
        ["mg","Oliveira"],	
        ["mg","Onca de Pitangui"],	
        ["mg","Oratorios"],	
        ["mg","Orizania"],	
        ["mg","Ouro Branco"],	
        ["mg","Ouro Fino"],	
        ["mg","Ouro Preto"],	
        ["mg","Ouro Verde de Minas"],	
        ["mg","Padre Carvalho"],	
        ["mg","Padre Paraiso"],	
        ["mg","Pai Pedro"],	
        ["mg","Paineiras"],	
        ["mg","Pains"],	
        ["mg","Paiva"],	
        ["mg","Palma"],	
        ["mg","Palmopolis"],	
        ["mg","Papagaios"],	
        ["mg","Para de Minas"],	
        ["mg","Paracatu"],	
        ["mg","Paraguacu"],	
        ["mg","Paraisopolis"],	
        ["mg","Paraopeba"],	
        ["mg","Passa Quatro"],	
        ["mg","Passa Tempo"],	
        ["mg","Passa Vinte"],	
        ["mg","Passabem"],	
        ["mg","Passos"],	
        ["mg","Patis"],	
        ["mg","Patos de Minas"],	
        ["mg","Patrocinio do Muriae"],	
        ["mg","Patrocinio"],	
        ["mg","Paula Candido"],	
        ["mg","Paulistas"],	
        ["mg","Pavao"],	
        ["mg","Pecanha"],	
        ["mg","Pedra Azul"],	
        ["mg","Pedra Bonita"],	
        ["mg","Pedra Dourada"],	
        ["mg","Pedra do Anta"],	
        ["mg","Pedra do Indaia"],	
        ["mg","Pedralva"],	
        ["mg","Pedras de Maria da Cruz"],	
        ["mg","Pedrinopolis"],	
        ["mg","Pedro Leopoldo"],	
        ["mg","Pedro Teixeira"],	
        ["mg","Pequeri"],	
        ["mg","Pequi"],	
        ["mg","Perdigao"],	
        ["mg","Perdizes"],	
        ["mg","Perdoes"],	
        ["mg","Periquito"],	
        ["mg","Pescador"],	
        ["mg","Piau"],	
        ["mg","Piedade de Caratinga"],	
        ["mg","Piedade de Ponte Nova"],	
        ["mg","Piedade do Rio Grande"],	
        ["mg","Piedade dos Gerais"],	
        ["mg","Pimenta"],	
        ["mg","Pingo d'Agua"],	
        ["mg","Pintopolis"],	
        ["mg","Piracema"],	
        ["mg","Pirajuba"],	
        ["mg","Piranga"],	
        ["mg","Pirangucu"],	
        ["mg","Piranguinho"],	
        ["mg","Pirapetinga"],	
        ["mg","Pirapora"],	
        ["mg","Pirauba"],	
        ["mg","Pitangui"],	
        ["mg","Piui"],	
        ["mg","Planura"],	
        ["mg","Poco Fundo"],	
        ["mg","Pocos de Caldas"],	
        ["mg","Pocrane"],	
        ["mg","Pompeu"],	
        ["mg","Ponte Nova"],	
        ["mg","Ponto Chique"],	
        ["mg","Ponto dos Volantes"],	
        ["mg","Porteirinha"],	
        ["mg","Porto Firme"],	
        ["mg","Pote"],	
        ["mg","Pouso Alegre"],	
        ["mg","Pouso Alto"],	
        ["mg","Prados"],	
        ["mg","Prata"],	
        ["mg","Pratapolis"],	
        ["mg","Pratinha"],	
        ["mg","Presidente Bernardes"],	
        ["mg","Presidente Juscelino"],	
        ["mg","Presidente Kubitschek"],	
        ["mg","Presidente Olegario"],	
        ["mg","Prudente de Morais"],	
        ["mg","Quartel Geral"],	
        ["mg","Queluzita"],	
        ["mg","Raposos"],	
        ["mg","Raul Soares"],	
        ["mg","Recreio"],	
        ["mg","Reduto"],	
        ["mg","Resende Costa"],	
        ["mg","Resplendor"],	
        ["mg","Ressaquinha"],	
        ["mg","Riachinho"],	
        ["mg","Riacho dos Machados"],	
        ["mg","Ribeirao Vermelho"],	
        ["mg","Ribeirao das Neves"],	
        ["mg","Rio Acima"],	
        ["mg","Rio Casca"],	
        ["mg","Rio Doce"],	
        ["mg","Rio Espera"],	
        ["mg","Rio Manso"],	
        ["mg","Rio Novo"],	
        ["mg","Rio Paranaiba"],	
        ["mg","Rio Pardo de Minas"],	
        ["mg","Rio Piracicaba"],	
        ["mg","Rio Pomba"],	
        ["mg","Rio Preto"],	
        ["mg","Rio Vermelho"],	
        ["mg","Rio do Prado"],	
        ["mg","Ritapolis"],	
        ["mg","Rochedo de Minas"],	
        ["mg","Rodeiro"],	
        ["mg","Romaria"],	
        ["mg","Rosario da Limeira"],	
        ["mg","Rubelita"],	
        ["mg","Rubim"],	
        ["mg","Sabara"],	
        ["mg","Sabinopolis"],	
        ["mg","Sacramento"],	
        ["mg","Salinas"],	
        ["mg","Salto da Divisa"],	
        ["mg","Santa Barbara do Leste"],	
        ["mg","Santa Barbara do Monte Verde"],	
        ["mg","Santa Barbara do Tugurio"],	
        ["mg","Santa Barbara"],	
        ["mg","Santa Cruz de Minas"],	
        ["mg","Santa Cruz de Salinas"],	
        ["mg","Santa Cruz do Escalvado"],	
        ["mg","Santa Efigenia de Minas"],	
        ["mg","Santa Fe de Minas"],	
        ["mg","Santa Helena de Minas"],	
        ["mg","Santa Juliana"],	
        ["mg","Santa Luzia"],	
        ["mg","Santa Margarida"],	
        ["mg","Santa Maria de Itabira"],	
        ["mg","Santa Maria do Salto"],	
        ["mg","Santa Maria do Suacui"],	
        ["mg","Santa Rita de Caldas"],	
        ["mg","Santa Rita de Ibitipoca"],	
        ["mg","Santa Rita de Jacutinga"],	
        ["mg","Santa Rita de Minas"],	
        ["mg","Santa Rita do Itueto"],	
        ["mg","Santa Rita do Sapucai"],	
        ["mg","Santa Rosa da Serra"],	
        ["mg","Santa Vitoria"],	
        ["mg","Santana da Vargem"],	
        ["mg","Santana de Cataguases"],	
        ["mg","Santana de Pirapama"],	
        ["mg","Santana do Deserto"],	
        ["mg","Santana do Garambeu"],	
        ["mg","Santana do Jacare"],	
        ["mg","Santana do Manhuacu"],	
        ["mg","Santana do Paraiso"],	
        ["mg","Santana do Riacho"],	
        ["mg","Santana dos Montes"],	
        ["mg","Santo Antonio do Amparo"],	
        ["mg","Santo Antonio do Aventureiro"],	
        ["mg","Santo Antonio do Grama"],	
        ["mg","Santo Antonio do Itambe"],	
        ["mg","Santo Antonio do Jacinto"],	
        ["mg","Santo Antonio do Monte"],	
        ["mg","Santo Antonio do Retiro"],	
        ["mg","Santo Antonio do Rio Abaixo"],	
        ["mg","Santo Hipolito"],	
        ["mg","Santos Dumont"],	
        ["mg","Sao Bento Abade"],	
        ["mg","Sao Bras do Suacui"],	
        ["mg","Sao Domingos das Dores"],	
        ["mg","Sao Domingos do Prata"],	
        ["mg","Sao Felix de Minas"],	
        ["mg","Sao Francisco de Paula"],	
        ["mg","Sao Francisco de Sales"],	
        ["mg","Sao Francisco do Gloria"],	
        ["mg","Sao Francisco"],	
        ["mg","Sao Geraldo da Piedade"],	
        ["mg","Sao Geraldo do Baixio"],	
        ["mg","Sao Geraldo"],	
        ["mg","Sao Goncalo do Abaete"],	
        ["mg","Sao Goncalo do Para"],	
        ["mg","Sao Goncalo do Rio Abaixo"],	
        ["mg","Sao Goncalo do Rio Preto"],	
        ["mg","Sao Goncalo do Sapucai"],	
        ["mg","Sao Gotardo"],	
        ["mg","Sao Joao Batista do Gloria"],	
        ["mg","Sao Joao Evangelista"],	
        ["mg","Sao Joao Nepomuceno"],	
        ["mg","Sao Joao da Lagoa"],	
        ["mg","Sao Joao da Mata"],	
        ["mg","Sao Joao da Ponte"],	
        ["mg","Sao Joao das Missoes"],	
        ["mg","Sao Joao del Rei"],	
        ["mg","Sao Joao do Manhuacu"],	
        ["mg","Sao Joao do Manteninha"],	
        ["mg","Sao Joao do Oriente"],	
        ["mg","Sao Joao do Pacui"],	
        ["mg","Sao Joao do Paraiso"],	
        ["mg","Sao Joaquim de Bicas"],	
        ["mg","Sao Jose da Barra"],	
        ["mg","Sao Jose da Lapa"],	
        ["mg","Sao Jose da Safira"],	
        ["mg","Sao Jose da Varginha"],	
        ["mg","Sao Jose do Alegre"],	
        ["mg","Sao Jose do Divino"],	
        ["mg","Sao Jose do Goiabal"],	
        ["mg","Sao Jose do Jacuri"],	
        ["mg","Sao Jose do Mantimento"],	
        ["mg","Sao Lourenco"],	
        ["mg","Sao Miguel do Anta"],	
        ["mg","Sao Pedro da Uniao"],	
        ["mg","Sao Pedro do Suacui"],	
        ["mg","Sao Pedro dos Ferros"],	
        ["mg","Sao Romao"],	
        ["mg","Sao Roque de Minas"],	
        ["mg","Sao Sebastiao da Bela Vista"],	
        ["mg","Sao Sebastiao da Vargem Alegre"],	
        ["mg","Sao Sebastiao do Anta"],	
        ["mg","Sao Sebastiao do Maranhao"],	
        ["mg","Sao Sebastiao do Oeste"],	
        ["mg","Sao Sebastiao do Paraiso"],	
        ["mg","Sao Sebastiao do Rio Preto"],	
        ["mg","Sao Sebastiao do Rio Verde"],	
        ["mg","Sao Thome das Letras"],	
        ["mg","Sao Tiago"],	
        ["mg","Sao Tomas de Aquino"],	
        ["mg","Sao Vicente de Minas"],	
        ["mg","Sapucai-Mirim"],	
        ["mg","Sardoa"],	
        ["mg","Sarzedo"],	
        ["mg","Sem-Peixe"],	
        ["mg","Senador Amaral"],	
        ["mg","Senador Cortes"],	
        ["mg","Senador Firmino"],	
        ["mg","Senador Jose Bento"],	
        ["mg","Senador Modestino Goncalves"],	
        ["mg","Senhora de Oliveira"],	
        ["mg","Senhora do Porto"],	
        ["mg","Senhora dos Remedios"],	
        ["mg","Sericita"],	
        ["mg","Seritinga"],	
        ["mg","Serra Azul de Minas"],	
        ["mg","Serra da Saudade"],	
        ["mg","Serra do Salitre"],	
        ["mg","Serra dos Aimores"],	
        ["mg","Serrania"],	
        ["mg","Serranopolis de Minas"],	
        ["mg","Serranos"],	
        ["mg","Serro"],	
        ["mg","Sete Lagoas"],	
        ["mg","Setubinha"],	
        ["mg","Silveirania"],	
        ["mg","Silvianopolis"],	
        ["mg","Simao Pereira"],	
        ["mg","Simonesia"],	
        ["mg","Sobralia"],	
        ["mg","Soledade de Minas"],	
        ["mg","Tabuleiro"],	
        ["mg","Taiobeiras"],	
        ["mg","Taparuba"],	
        ["mg","Tapira"],	
        ["mg","Tapirai"],	
        ["mg","Taquaracu de Minas"],	
        ["mg","Tarumirim"],	
        ["mg","Teixeiras"],	
        ["mg","Teofilo Otoni"],	
        ["mg","Timoteo"],	
        ["mg","Tiradentes"],	
        ["mg","Tiros"],	
        ["mg","Tocantins"],	
        ["mg","Tocos do Moji"],	
        ["mg","Toledo"],	
        ["mg","Tombos"],	
        ["mg","Tres Coracoes"],	
        ["mg","Tres Marias"],	
        ["mg","Tres Pontas"],	
        ["mg","Tumiritinga"],	
        ["mg","Tupaciguara"],	
        ["mg","Turmalina"],	
        ["mg","Turvolandia"],	
        ["mg","Uba"],	
        ["mg","Ubai"],	
        ["mg","Ubaporanga"],	
        ["mg","Uberaba"],	
        ["mg","Uberlandia"],	
        ["mg","Umburatiba"],	
        ["mg","Unai"],	
        ["mg","Uniao de Minas"],	
        ["mg","Uruana de Minas"],	
        ["mg","Urucania"],	
        ["mg","Urucuia"],	
        ["mg","Vargem Alegre"],	
        ["mg","Vargem Bonita"],	
        ["mg","Vargem Grande do Rio Pardo"],	
        ["mg","Varginha"],	
        ["mg","Varjao de MInas"],	
        ["mg","Varzea da Palma"],	
        ["mg","Varzelandia"],	
        ["mg","Vazante"],	
        ["mg","Verdelandia"],	
        ["mg","Veredinha"],	
        ["mg","Verissimo"],	
        ["mg","Vermelho Novo"],	
        ["mg","Vespasiano"],	
        ["mg","Vicosa"],	
        ["mg","Vieiras"],	
        ["mg","Virgem da Lapa"],	
        ["mg","Virginia"],	
        ["mg","Virginopolis"],	
        ["mg","Virgolandia"],	
        ["mg","Visconde do Rio Branco"],	
        ["mg","Volta Grande"],	
        ["mg","Wenceslau Braz"],	
        ["rj","Angra dos Reis"],	
        ["rj","Aperibé"],	
        ["rj","Araruama"],	
        ["rj","Areal"],	
        ["rj","Armação dos Búzios"],	
        ["rj","Arraial do Cabo"],	
        ["rj","Barra do Piraí"],	
        ["rj","Barra Mansa"],	
        ["rj","Belford Roxo"],	
        ["rj","Bom Jardim"],	
        ["rj","Bom Jesus do Itabapoana"],	
        ["rj","Cabo Frio"],	
        ["rj","Cachoeiras de Macacu"],	
        ["rj","Cambuci"],	
        ["rj","Campos dos Goytacazes"],	
        ["rj","Cantagalo"],	
        ["rj","Carapebus"],	
        ["rj","Cardoso Moreira"],	
        ["rj","Carmo"],	
        ["rj","Casimiro de Abreu"],	
        ["rj","Comendador Levy Gasparian"],	
        ["rj","Conceição de Macabu"],	
        ["rj","Cordeiro"],	
        ["rj","Duas Barras"],	
        ["rj","Duque de Caxias"],	
        ["rj","Engenheiro Paulo de Frontin"],	
        ["rj","Guapimirim"],	
        ["rj","Iguaba Grande"],	
        ["rj","Itaboraí"],	
        ["rj","Itaguaí"],	
        ["rj","Italva"],	
        ["rj","Itaocara"],	
        ["rj","Itaperuna"],	
        ["rj","Itatiaia"],	
        ["rj","Japeri"],	
        ["rj","Laje do Muriaé"],	
        ["rj","Macaé"],	
        ["rj","Macuco"],	
        ["rj","Magé"],	
        ["rj","Mangaratiba"],	
        ["rj","Maricá"],	
        ["rj","Mendes"],	
        ["rj","Mesquita"],	
        ["rj","Miguel Pereira"],	
        ["rj","Miracema"],	
        ["rj","Natividade"],	
        ["rj","Nilópolis"],	
        ["rj","Niterói"],	
        ["rj","Nova Friburgo"],	
        ["rj","Nova Iguaçu"],	
        ["rj","Paracambi"],	
        ["rj","Paraíba do Sul"],	
        ["rj","Paraty"],	
        ["rj","Paty do Alferes"],	
        ["rj","Petrópolis"],	
        ["rj","Pinheiral"],	
        ["rj","Piraí"],	
        ["rj","Porciúncula"],	
        ["rj","Porto Real"],	
        ["rj","Quatis"],	
        ["rj","Queimados"],	
        ["rj","Quissamã"],	
        ["rj","Resende"],	
        ["rj","Rio Bonito"],	
        ["rj","Rio Claro"],	
        ["rj","Rio das Flores"],	
        ["rj","Rio das Ostras"],	
        ["rj","Rio de Janeiro"],	
        ["rj","Santa Maria Madalena"],	
        ["rj","Santo Antônio de Pádua"],	
        ["rj","São Fidélis"],	
        ["rj","São Francisco de Itabapoana"],	
        ["rj","São Gonçalo"],	
        ["rj","São João da Barra"],	
        ["rj","São João de Meriti"],	
        ["rj","São José de Ubá"],	
        ["rj","São José do Vale do Rio Preto"],	
        ["rj","São Pedro da Aldeia"],	
        ["rj","São Sebastião do Alto"],	
        ["rj","Sapucaia"],	
        ["rj","Saquarema"],	
        ["rj","Seropédica"],	
        ["rj","Silva Jardim"],	
        ["rj","Sumidouro"],	
        ["rj","Tanguá"],	
        ["rj","Teresópolis"],	
        ["rj","Trajano de Moraes"],	
        ["rj","Três Rios"],	
        ["rj","Valença"],	
        ["rj","Varre-Sai"],	
        ["rj","Vassouras"],	
        ["rj","Volta Redonda"],	
        ["sp","Adamantina"],	
        ["sp","Adolfo"],	
        ["sp","Aguaí"],	
        ["sp","Águas da Prata"],	
        ["sp","Águas de Lindóia"],	
        ["sp","Águas de Santa Bárbara"],	
        ["sp","Águas de São Pedro"],	
        ["sp","Agudos"],	
        ["sp","Alambari"],	
        ["sp","Alfredo Marcondes"],	
        ["sp","Altair"],	
        ["sp","Altinópolis"],	
        ["sp","Alto Alegre"],	
        ["sp","Alumínio"],	
        ["sp","Álvares Florence"],	
        ["sp","Álvares Machado"],	
        ["sp","Álvaro de Carvalho"],	
        ["sp","Alvinlândia"],	
        ["sp","Americana"],	
        ["sp","Américo Brasiliense"],	
        ["sp","Américo de Campos"],	
        ["sp","Amparo"],	
        ["sp","Analândia"],	
        ["sp","Andradina"],	
        ["sp","Angatuba"],	
        ["sp","Anhembi"],	
        ["sp","Anhumas"],	
        ["sp","Aparecida"],	
        ["sp","Aparecida d'Oeste"],	
        ["sp","Apiaí"],	
        ["sp","Araçariguama"],	
        ["sp","Araçatuba"],	
        ["sp","Araçoiaba da Serra"],	
        ["sp","Aramina"],	
        ["sp","Arandu"],	
        ["sp","Arapeí"],	
        ["sp","Araraquara"],	
        ["sp","Araras"],	
        ["sp","Arco-Íris"],	
        ["sp","Arealva"],	
        ["sp","Areias"],	
        ["sp","Areiópolis"],	
        ["sp","Ariranha"],	
        ["sp","Artur Nogueira"],	
        ["sp","Arujá"],	
        ["sp","Aspásia"],	
        ["sp","Assis"],	
        ["sp","Atibaia"],	
        ["sp","Auriflama"],	
        ["sp","Avaí"],	
        ["sp","Avanhandava"],	
        ["sp","Avaré"],	
        ["sp","Bady Bassitt"],	
        ["sp","Balbinos"],	
        ["sp","Bálsamo"],	
        ["sp","Bananal"],	
        ["sp","Barão de Antonina"],	
        ["sp","Barbosa"],	
        ["sp","Bariri"],	
        ["sp","Barra Bonita"],	
        ["sp","Barra do Chapéu"],	
        ["sp","Barra do Turvo"],	
        ["sp","Barretos"],	
        ["sp","Barrinha"],	
        ["sp","Barueri"],	
        ["sp","Bastos"],	
        ["sp","Batatais"],	
        ["sp","Bauru"],	
        ["sp","Bebedouro"],	
        ["sp","Bento de Abreu"],	
        ["sp","Bernardino de Campos"],	
        ["sp","Bertioga"],	
        ["sp","Bilac"],	
        ["sp","Birigui"],	
        ["sp","Biritiba Mirim"],	
        ["sp","Boa Esperança do Sul"],	
        ["sp","Bocaina"],	
        ["sp","Bofete"],	
        ["sp","Boituva"],	
        ["sp","Bom Jesus dos Perdões"],	
        ["sp","Bom Sucesso de Itararé"],	
        ["sp","Borá"],	
        ["sp","Boraceia"],	
        ["sp","Borborema"],	
        ["sp","Borebi"],	
        ["sp","Botucatu"],	
        ["sp","Bragança Paulista"],	
        ["sp","Braúna"],	
        ["sp","Brejo Alegre"],	
        ["sp","Brodowski"],	
        ["sp","Brotas"],	
        ["sp","Buri"],	
        ["sp","Buritama"],	
        ["sp","Buritizal"],	
        ["sp","Cabrália Paulista"],	
        ["sp","Cabreúva"],	
        ["sp","Caçapava"],	
        ["sp","Cachoeira Paulista"],	
        ["sp","Caconde"],	
        ["sp","Cafelândia"],	
        ["sp","Caiabu"],	
        ["sp","Caieiras"],	
        ["sp","Caiuá"],	
        ["sp","Cajamar"],	
        ["sp","Cajati"],	
        ["sp","Cajobi"],	
        ["sp","Cajuru"],	
        ["sp","Campina do Monte Alegre"],	
        ["sp","Campinas"],	
        ["sp","Campo Limpo Paulista"],	
        ["sp","Campos do Jordão"],	
        ["sp","Campos Novos Paulista"],	
        ["sp","Cananéia"],	
        ["sp","Canas"],	
        ["sp","Cândido Mota"],	
        ["sp","Cândido Rodrigues"],	
        ["sp","Canitar"],	
        ["sp","Capão Bonito"],	
        ["sp","Capela do Alto"],	
        ["sp","Capivari"],	
        ["sp","Caraguatatuba"],	
        ["sp","Carapicuíba"],	
        ["sp","Cardoso"],	
        ["sp","Casa Branca"],	
        ["sp","Cássia dos Coqueiros"],	
        ["sp","Castilho"],	
        ["sp","Catanduva"],	
        ["sp","Catiguá"],	
        ["sp","Cedral"],	
        ["sp","Cerqueira César"],	
        ["sp","Cerquilho"],	
        ["sp","Cesário Lange"],	
        ["sp","Charqueada"],	
        ["sp","Chavantes"],	
        ["sp","Clementina"],	
        ["sp","Colina"],	
        ["sp","Colômbia"],	
        ["sp","Conchal"],	
        ["sp","Conchas"],	
        ["sp","Cordeirópolis"],	
        ["sp","Coroados"],	
        ["sp","Coronel Macedo"],	
        ["sp","Corumbataí"],	
        ["sp","Cosmópolis"],	
        ["sp","Cosmorama"],	
        ["sp","Cotia"],	
        ["sp","Cravinhos"],	
        ["sp","Cristais Paulista"],	
        ["sp","Cruzália"],	
        ["sp","Cruzeiro"],	
        ["sp","Cubatão"],	
        ["sp","Cunha"],	
        ["sp","Descalvado"],	
        ["sp","Diadema"],	
        ["sp","Dirce Reis"],	
        ["sp","Divinolândia"],	
        ["sp","Dobrada"],	
        ["sp","Dois Córregos"],	
        ["sp","Dolcinópolis"],	
        ["sp","Dourado"],	
        ["sp","Dracena"],	
        ["sp","Duartina"],	
        ["sp","Dumont"],	
        ["sp","Echaporã"],	
        ["sp","Eldorado"],	
        ["sp","Elias Fausto"],	
        ["sp","Elisiário"],	
        ["sp","Embaúba"],	
        ["sp","Embu das Artes"],	
        ["sp","Embu-Guaçu"],	
        ["sp","Emilianópolis"],	
        ["sp","Engenheiro Coelho"],	
        ["sp","Espírito Santo do Pinhal"],	
        ["sp","Espírito Santo do Turvo"],	
        ["sp","Estiva Gerbi"],	
        ["sp","Estrela d'Oeste"],	
        ["sp","Estrela do Norte"],	
        ["sp","Euclides da Cunha Paulista"],	
        ["sp","Fartura"],	
        ["sp","Fernando Prestes"],	
        ["sp","Fernandópolis"],	
        ["sp","Fernão"],	
        ["sp","Ferraz de Vasconcelos"],	
        ["sp","Flora Rica"],	
        ["sp","Floreal"],	
        ["sp","Flórida Paulista"],	
        ["sp","Florínea"],	
        ["sp","Franca"],	
        ["sp","Francisco Morato"],	
        ["sp","Franco da Rocha"],	
        ["sp","Gabriel Monteiro"],	
        ["sp","Gália"],	
        ["sp","Garça"],	
        ["sp","Gastão Vidigal"],	
        ["sp","Gavião Peixoto"],	
        ["sp","General Salgado"],	
        ["sp","Getulina"],	
        ["sp","Glicério"],	
        ["sp","Guaiçara"],	
        ["sp","Guaimbê"],	
        ["sp","Guaíra"],	
        ["sp","Guapiaçu"],	
        ["sp","Guapiara"],	
        ["sp","Guará"],	
        ["sp","Guaraçaí"],	
        ["sp","Guaraci"],	
        ["sp","Guarani d'Oeste"],	
        ["sp","Guarantã"],	
        ["sp","Guararapes"],	
        ["sp","Guararema"],	
        ["sp","Guaratinguetá"],	
        ["sp","Guareí"],	
        ["sp","Guariba"],	
        ["sp","Guarujá"],	
        ["sp","Guarulhos"],	
        ["sp","Guatapará"],	
        ["sp","Guzolândia"],	
        ["sp","Herculândia"],	
        ["sp","Holambra"],	
        ["sp","Hortolândia"],	
        ["sp","Iacanga"],	
        ["sp","Iacri"],	
        ["sp","Iaras"],	
        ["sp","Ibaté"],	
        ["sp","Ibirá"],	
        ["sp","Ibirarema"],	
        ["sp","Ibitinga"],	
        ["sp","Ibiúna"],	
        ["sp","Icém"],	
        ["sp","Iepê"],	
        ["sp","Igaraçu do Tietê"],	
        ["sp","Igarapava"],	
        ["sp","Igaratá"],	
        ["sp","Iguape"],	
        ["sp","Ilha Comprida"],	
        ["sp","Ilha Solteira"],	
        ["sp","Ilhabela"],	
        ["sp","Indaiatuba"],	
        ["sp","Indiana"],	
        ["sp","Indiaporã"],	
        ["sp","Inúbia Paulista"],	
        ["sp","Ipaussu"],	
        ["sp","Iperó"],	
        ["sp","Ipeúna"],	
        ["sp","Ipiguá"],	
        ["sp","Iporanga"],	
        ["sp","Ipuã"],	
        ["sp","Iracemápolis"],	
        ["sp","Irapuã"],	
        ["sp","Irapuru"],	
        ["sp","Itaberá"],	
        ["sp","Itaí"],	
        ["sp","Itajobi"],	
        ["sp","Itaju"],	
        ["sp","Itanhaém"],	
        ["sp","Itaoca"],	
        ["sp","Itapecerica da Serra"],	
        ["sp","Itapetininga"],	
        ["sp","Itapeva"],	
        ["sp","Itapevi"],	
        ["sp","Itapira"],	
        ["sp","Itapirapuã Paulista"],	
        ["sp","Itápolis"],	
        ["sp","Itaporanga"],	
        ["sp","Itapuí"],	
        ["sp","Itapura"],	
        ["sp","Itaquaquecetuba"],	
        ["sp","Itararé"],	
        ["sp","Itariri"],	
        ["sp","Itatiba"],	
        ["sp","Itatinga"],	
        ["sp","Itirapina"],	
        ["sp","Itirapuã"],	
        ["sp","Itobi"],	
        ["sp","Itu"],	
        ["sp","Itupeva"],	
        ["sp","Ituverava"],	
        ["sp","Jaborandi"],	
        ["sp","Jaboticabal"],	
        ["sp","Jacareí"],	
        ["sp","Jaci"],	
        ["sp","Jacupiranga"],	
        ["sp","Jaguariúna"],	
        ["sp","Jales"],	
        ["sp","Jambeiro"],	
        ["sp","Jandira"],	
        ["sp","Jardinópolis"],	
        ["sp","Jarinu"],	
        ["sp","Jaú"],	
        ["sp","Jeriquara"],	
        ["sp","Joanópolis"],	
        ["sp","João Ramalho"],	
        ["sp","José Bonifácio"],	
        ["sp","Júlio Mesquita"],	
        ["sp","Jumirim"],	
        ["sp","Jundiaí"],	
        ["sp","Junqueirópolis"],	
        ["sp","Juquiá"],	
        ["sp","Juquitiba"],	
        ["sp","Lagoinha"],	
        ["sp","Laranjal Paulista"],	
        ["sp","Lavínia"],	
        ["sp","Lavrinhas"],	
        ["sp","Leme"],	
        ["sp","Lençóis Paulista"],	
        ["sp","Limeira"],	
        ["sp","Lindoia"],	
        ["sp","Lins"],	
        ["sp","Lorena"],	
        ["sp","Lourdes"],	
        ["sp","Louveira"],	
        ["sp","Lucélia"],	
        ["sp","Lucianópolis"],	
        ["sp","Luiz Antônio"],	
        ["sp","Luiziânia"],	
        ["sp","Lupércio"],	
        ["sp","Lutécia"],	
        ["sp","Macatuba"],	
        ["sp","Macaubal"],	
        ["sp","Macedônia"],	
        ["sp","Magda"],	
        ["sp","Mairinque"],	
        ["sp","Mairiporã"],	
        ["sp","Manduri"],	
        ["sp","Marabá Paulista"],	
        ["sp","Maracaí"],	
        ["sp","Marapoama"],	
        ["sp","Mariápolis"],	
        ["sp","Marília"],	
        ["sp","Marinópolis"],	
        ["sp","Martinópolis"],	
        ["sp","Matão"],	
        ["sp","Mauá"],	
        ["sp","Mendonça"],	
        ["sp","Meridiano"],	
        ["sp","Mesópolis"],	
        ["sp","Miguelópolis"],	
        ["sp","Mineiros do Tietê"],	
        ["sp","Mira Estrela"],	
        ["sp","Miracatu"],	
        ["sp","Mirandópolis"],	
        ["sp","Mirante do Paranapanema"],	
        ["sp","Mirassol"],	
        ["sp","Mirassolândia"],	
        ["sp","Mococa"],	
        ["sp","Mogi das Cruzes"],	
        ["sp","Mogi Guaçu"],	
        ["sp","Mogi Mirim"],	
        ["sp","Mombuca"],	
        ["sp","Monções"],	
        ["sp","Mongaguá"],	
        ["sp","Monte Alegre do Sul"],	
        ["sp","Monte Alto"],	
        ["sp","Monte Aprazível"],	
        ["sp","Monte Azul Paulista"],	
        ["sp","Monte Castelo"],	
        ["sp","Monte Mor"],	
        ["sp","Monteiro Lobato"],	
        ["sp","Morro Agudo"],	
        ["sp","Morungaba"],	
        ["sp","Motuca"],	
        ["sp","Murutinga do Sul"],	
        ["sp","Nantes"],	
        ["sp","Narandiba"],	
        ["sp","Natividade da Serra"],	
        ["sp","Nazaré Paulista"],	
        ["sp","Neves Paulista"],	
        ["sp","Nhandeara"],	
        ["sp","Nipoã"],	
        ["sp","Nova Aliança"],	
        ["sp","Nova Campina"],	
        ["sp","Nova Canaã Paulista"],	
        ["sp","Nova Castilho"],	
        ["sp","Nova Europa"],	
        ["sp","Nova Granada"],	
        ["sp","Nova Guataporanga"],	
        ["sp","Nova Independência"],	
        ["sp","Nova Luzitânia"],	
        ["sp","Nova Odessa"],	
        ["sp","Novais"],	
        ["sp","Novo Horizonte"],	
        ["sp","Nuporanga"],	
        ["sp","Ocauçu"],	
        ["sp","Óleo"],	
        ["sp","Olímpia"],	
        ["sp","Onda Verde"],	
        ["sp","Oriente"],	
        ["sp","Orindiúva"],	
        ["sp","Orlândia"],	
        ["sp","Osasco"],	
        ["sp","Oscar Bressane"],	
        ["sp","Osvaldo Cruz"],	
        ["sp","Ourinhos"],	
        ["sp","Ouro Verde"],	
        ["sp","Ouroeste"],	
        ["sp","Pacaembu"],	
        ["sp","Palestina"],	
        ["sp","Palmares Paulista"],	
        ["sp","Palmeira d'Oeste"],	
        ["sp","Palmital"],	
        ["sp","Panorama"],	
        ["sp","Paraguaçu Paulista"],	
        ["sp","Paraibuna"],	
        ["sp","Paraíso"],	
        ["sp","Paranapanema"],	
        ["sp","Paranapuã"],	
        ["sp","Parapuã"],	
        ["sp","Pardinho"],	
        ["sp","Pariquera-Açu"],	
        ["sp","Parisi"],	
        ["sp","Patrocínio Paulista"],	
        ["sp","Paulicéia"],	
        ["sp","Paulínia"],	
        ["sp","Paulistânia"],	
        ["sp","Paulo de Faria"],	
        ["sp","Pederneiras"],	
        ["sp","Pedra Bela"],	
        ["sp","Pedranópolis"],	
        ["sp","Pedregulho"],	
        ["sp","Pedreira"],	
        ["sp","Pedrinhas Paulista"],	
        ["sp","Pedro de Toledo"],	
        ["sp","Penápolis"],	
        ["sp","Pereira Barreto"],	
        ["sp","Pereiras"],	
        ["sp","Peruíbe"],	
        ["sp","Piacatu"],	
        ["sp","Piedade"],	
        ["sp","Pilar do Sul"],	
        ["sp","Pindamonhangaba"],	
        ["sp","Pindorama"],	
        ["sp","Pinhalzinho"],	
        ["sp","Piquerobi"],	
        ["sp","Piquete"],	
        ["sp","Piracaia"],	
        ["sp","Piracicaba"],	
        ["sp","Piraju"],	
        ["sp","Pirajuí"],	
        ["sp","Pirangi"],	
        ["sp","Pirapora do Bom Jesus"],	
        ["sp","Pirapozinho"],	
        ["sp","Pirassununga"],	
        ["sp","Piratininga"],	
        ["sp","Pitangueiras"],	
        ["sp","Planalto"],	
        ["sp","Platina"],	
        ["sp","Poá"],	
        ["sp","Poloni"],	
        ["sp","Pompeia"],	
        ["sp","Pongaí"],	
        ["sp","Pontal"],	
        ["sp","Pontalinda"],	
        ["sp","Pontes Gestal"],	
        ["sp","Populina"],	
        ["sp","Porangaba"],	
        ["sp","Porto Feliz"],	
        ["sp","Porto Ferreira"],	
        ["sp","Potim"],	
        ["sp","Potirendaba"],	
        ["sp","Pracinha"],	
        ["sp","Pradópolis"],	
        ["sp","Praia Grande"],	
        ["sp","Pratânia"],	
        ["sp","Presidente Alves"],	
        ["sp","Presidente Bernardes"],	
        ["sp","Presidente Epitácio"],	
        ["sp","Presidente Prudente"],	
        ["sp","Presidente Venceslau"],	
        ["sp","Promissão"],	
        ["sp","Quadra"],	
        ["sp","Quatá"],	
        ["sp","Queiroz"],	
        ["sp","Queluz"],	
        ["sp","Quintana"],	
        ["sp","Rafard"],	
        ["sp","Rancharia"],	
        ["sp","Redenção da Serra"],	
        ["sp","Regente Feijó"],	
        ["sp","Reginópolis"],	
        ["sp","Registro"],	
        ["sp","Restinga"],	
        ["sp","Ribeira"],	
        ["sp","Ribeirão Bonito"],	
        ["sp","Ribeirão Branco"],	
        ["sp","Ribeirão Corrente"],	
        ["sp","Ribeirão do Sul"],	
        ["sp","Ribeirão dos Índios"],	
        ["sp","Ribeirão Grande"],	
        ["sp","Ribeirão Pires"],	
        ["sp","Ribeirão Preto"],	
        ["sp","Rifaina"],	
        ["sp","Rincão"],	
        ["sp","Rinópolis"],	
        ["sp","Rio Claro"],	
        ["sp","Rio das Pedras"],	
        ["sp","Rio Grande da Serra"],	
        ["sp","Riolândia"],	
        ["sp","Riversul"],	
        ["sp","Rosana"],	
        ["sp","Roseira"],	
        ["sp","Rubiácea"],	
        ["sp","Rubinéia"],	
        ["sp","Sabino"],	
        ["sp","Sagres"],	
        ["sp","Sales"],	
        ["sp","Sales Oliveira"],	
        ["sp","Salesópolis"],	
        ["sp","Salmourão"],	
        ["sp","Saltinho"],	
        ["sp","Salto"],	
        ["sp","Salto de Pirapora"],	
        ["sp","Salto Grande"],	
        ["sp","Sandovalina"],	
        ["sp","Santa Adélia"],	
        ["sp","Santa Albertina"],	
        ["sp","Santa Bárbara d'Oeste"],	
        ["sp","Santa Branca"],	
        ["sp","Santa Clara d'Oeste"],	
        ["sp","Santa Cruz da Conceição"],	
        ["sp","Santa Cruz da Esperança"],	
        ["sp","Santa Cruz das Palmeiras"],	
        ["sp","Santa Cruz do Rio Pardo"],	
        ["sp","Santa Ernestina"],	
        ["sp","Santa Fé do Sul"],	
        ["sp","Santa Gertrudes"],	
        ["sp","Santa Isabel"],	
        ["sp","Santa Lúcia"],	
        ["sp","Santa Maria da Serra"],	
        ["sp","Santa Mercedes"],	
        ["sp","Santa Rita d'Oeste"],	
        ["sp","Santa Rita do Passa Quatro"],	
        ["sp","Santa Rosa de Viterbo"],	
        ["sp","Santa Salete"],	
        ["sp","Santana da Ponte Pensa"],	
        ["sp","Santana de Parnaíba"],	
        ["sp","Santo Anastácio"],	
        ["sp","Santo André"],	
        ["sp","Santo Antônio da Alegria"],	
        ["sp","Santo Antônio de Posse"],	
        ["sp","Santo Antônio do Aracanguá"],	
        ["sp","Santo Antônio do Jardim"],	
        ["sp","Santo Antônio do Pinhal"],	
        ["sp","Santo Expedito"],	
        ["sp","Santópolis do Aguapeí"],	
        ["sp","Santos"],	
        ["sp","São Bento do Sapucaí"],	
        ["sp","São Bernardo do Campo"],	
        ["sp","São Caetano do Sul"],	
        ["sp","São Carlos"],	
        ["sp","São Francisco"],	
        ["sp","São João da Boa Vista"],	
        ["sp","São João das Duas Pontes"],	
        ["sp","São João de Iracema"],	
        ["sp","São João do Pau-d'Alho"],	
        ["sp","São Joaquim da Barra"],	
        ["sp","São José da Bela Vista"],	
        ["sp","São José do Barreiro"],	
        ["sp","São José do Rio Pardo"],	
        ["sp","São José do Rio Preto"],	
        ["sp","São José dos Campos"],	
        ["sp","São Lourenço da Serra"],	
        ["sp","São Luiz do Paraitinga"],	
        ["sp","São Manuel"],	
        ["sp","São Miguel Arcanjo"],	
        ["sp","São Paulo"],	
        ["sp","São Pedro"],	
        ["sp","São Pedro do Turvo"],	
        ["sp","São Roque"],	
        ["sp","São Sebastião"],	
        ["sp","São Sebastião da Grama"],	
        ["sp","São Simão"],	
        ["sp","São Vicente"],	
        ["sp","Sarapuí"],	
        ["sp","Sarutaiá"],	
        ["sp","Sebastianópolis do Sul"],	
        ["sp","Serra Azul"],	
        ["sp","Serra Negra"],	
        ["sp","Serrana"],	
        ["sp","Sertãozinho"],	
        ["sp","Sete Barras"],	
        ["sp","Severínia"],	
        ["sp","Silveiras"],	
        ["sp","Socorro"],	
        ["sp","Sorocaba"],	
        ["sp","Sud Mennucci"],	
        ["sp","Sumaré"],	
        ["sp","Suzanápolis"],	
        ["sp","Suzano"],	
        ["sp","Tabapuã"],	
        ["sp","Tabatinga"],	
        ["sp","Taboão da Serra"],	
        ["sp","Taciba"],	
        ["sp","Taguaí"],	
        ["sp","Taiaçu"],	
        ["sp","Taiúva"],	
        ["sp","Tambaú"],	
        ["sp","Tanabi"],	
        ["sp","Tapiraí"],	
        ["sp","Tapiratiba"],	
        ["sp","Taquaral"],	
        ["sp","Taquaritinga"],	
        ["sp","Taquarituba"],	
        ["sp","Taquarivaí"],	
        ["sp","Tarabai"],	
        ["sp","Tarumã"],	
        ["sp","Tatuí"],	
        ["sp","Taubaté"],	
        ["sp","Tejupá"],	
        ["sp","Teodoro Sampaio"],	
        ["sp","Terra Roxa"],	
        ["sp","Tietê"],	
        ["sp","Timburi"],	
        ["sp","Torre de Pedra"],	
        ["sp","Torrinha"],	
        ["sp","Trabiju"],	
        ["sp","Tremembé"],	
        ["sp","Três Fronteiras"],	
        ["sp","Tuiuti"],	
        ["sp","Tupã"],	
        ["sp","Tupi Paulista"],	
        ["sp","Turiúba"],	
        ["sp","Turmalina"],	
        ["sp","Ubarana"],	
        ["sp","Ubatuba"],	
        ["sp","Ubirajara"],	
        ["sp","Uchoa"],	
        ["sp","União Paulista"],	
        ["sp","Urânia"],	
        ["sp","Uru"],	
        ["sp","Urupês"],	
        ["sp","Valentim Gentil"],	
        ["sp","Valinhos"],	
        ["sp","Valparaíso"],	
        ["sp","Vargem"],	
        ["sp","Vargem Grande do Sul"],	
        ["sp","Vargem Grande Paulista"],	
        ["sp","Várzea Paulista"],	
        ["sp","Vera Cruz"],	
        ["sp","Vinhedo"],	
        ["sp","Viradouro"],	
        ["sp","Vista Alegre do Alto"],	
        ["sp","Vitória Brasil"],	
        ["sp","Votorantim"],	
        ["sp","Votuporanga"],	
        ["sp","Zacarias"],	
        ["es","Afonso Cláudio"],	
        ["es","Água Doce do Norte"],	
        ["es","Águia Branca"],	
        ["es","Alegre"],	
        ["es","Alfredo Chaves"],	
        ["es","Alto Rio Novo"],	
        ["es","Anchieta"],	
        ["es","Apiacá"],	
        ["es","Aracruz"],	
        ["es","Atílio Vivácqua"],	
        ["es","Baixo Guandu"],	
        ["es","Barra de São Francisco"],	
        ["es","Boa Esperança"],	
        ["es","Bom Jesus do Norte"],	
        ["es","Brejetuba"],	
        ["es","Cachoeiro de Itapemirim"],	
        ["es","Cariacica"],	
        ["es","Castelo"],	
        ["es","Colatina"],	
        ["es","Conceição da Barra"],	
        ["es","Conceição do Castelo"],	
        ["es","Divino de São Lourenço"],	
        ["es","Domingos Martins"],	
        ["es","Dores do Rio Preto"],	
        ["es","Ecoporanga"],	
        ["es","Fundão"],	
        ["es","Guaçuí"],	
        ["es","Guarapari"],	
        ["es","Ibatiba"],	
        ["es","Ibiraçu"],	
        ["es","Ibitirama"],	
        ["es","Iconha"],	
        ["es","Irupi"],	
        ["es","Itaguaçu"],	
        ["es","Itapemirim"],	
        ["es","Itarana"],	
        ["es","Iúna"],	
        ["es","Jaguaré"],	
        ["es","Jerônimo Monteiro"],	
        ["es","João Neiva"],	
        ["es","Laranja da Terra"],	
        ["es","Linhares"],	
        ["es","Mantenópolis"],	
        ["es","Marataízes"],	
        ["es","Marechal Floriano"],	
        ["es","Marilândia"],	
        ["es","Mimoso do Sul"],	
        ["es","Montanha"],	
        ["es","Mucurici"],	
        ["es","Muniz Freire"],	
        ["es","Muqui"],	
        ["es","Nova Venécia"],	
        ["es","Pancas"],	
        ["es","Pedro Canário"],	
        ["es","Pinheiros"],	
        ["es","Piúma"],	
        ["es","Ponto Belo"],	
        ["es","Presidente Kennedy"],	
        ["es","Rio Bananal"],	
        ["es","Rio Novo do Sul"],	
        ["es","Santa Leopoldina"],	
        ["es","Santa Maria de Jetibá"],	
        ["es","Santa Teresa"],	
        ["es","São Domingos do Norte"],	
        ["es","São Gabriel da Palha"],	
        ["es","São José do Calçado"],	
        ["es","São Mateus"],	
        ["es","São Roque do Canaã"],	
        ["es","Serra"],	
        ["es","Sooretama"],	
        ["es","Vargem Alta"],	
        ["es","Venda Nova do Imigrante"],	
        ["es","Viana"],	
        ["es","Vila Pavão"],	
        ["es","Vila Valério"],	
        ["es","Vila Velha"],	
        ["es","Vitória"],	
    ]


    var quais_opt_municipio = []
    var estado_escolhido = x.value


    municipios_por_estado.forEach((item, index) => {
        if(item[0] == estado_escolhido){
            quais_opt_municipio.push(item[1])
        }
    })

    //apaga para não ficar nada na memória
    document.getElementById("municipio").innerHTML = ''


    quais_opt_municipio.forEach((item, index) =>{
        document.getElementById("municipio").innerHTML += `
        <option> ` + item + `</option>
        `
    })
    console.log(quais_opt_municipio)
}

//funções para ver se os campos funcionam
function getMunicipio(){
    var recebeMunicipio = document.getElementById("municipio").value
    console.log(recebeMunicipio)
    
}


function getFaixaEtaria(){
    var recebeFaixa = document.getElementById("faixaetaria").value
    console.log(recebeFaixa)
}

function getAbordagem(){
    var recebeAbordagem = document.getElementById("abordagem").value
    console.log(recebeAbordagem)
}

function getProntoAtendimento(){
const recebeProntoAtendimento = document.getElementsByName("prontoatendimento")
recebeProntoAtendimento.forEach(prontoatendimento =>{
    prontoatendimento.addEventListener('click', ()=>{
        console.log(prontoatendimento.value)
    })  
})
}

//Enviar o formulário
let myForm = document.getElementById('myform')

//pega elementos
let estado = document.getElementById("estado")
let municipio = document.getElementById("municipio")
let faixa = document.getElementById("faixaetaria")
let abordagem = document.getElementById("abordagem")
let pa = document.querySelector('input[name="prontoatendimento"]:checked')

//tags de erro para campo vazio
let estado_error = document.getElementById("estado_error")
let municipio_error = document.getElementById("municipio_error")
let abordagem_error = document.getElementById("abordagem_error")
let faixaetaria_error = document.getElementById("faixaetaria_error")
let pa_error = document.getElementById("pa_error")


myForm.addEventListener('submit', (e) =>{
    
    //Mensagens de erro para campo vazio


    if(estado.value === 'selecione' || estado.value === null)
    
    {
        e.preventDefault()
        estado_error.innerHTML = 'Preencha o campo'
    }
    else{
        estado_error.innerHTML = ''
    }

    if(municipio.value === '' || municipio.value === null)
    {
        e.preventDefault()
        municipio_error.innerHTML = 'Preencha este campo'
    }
    else{
        municipio_error.innerHTML = ''
    }

    if(faixa.value === 'selecione' || faixa.value === null)
    {
        e.preventDefault()
        faixaetaria_error.innerHTML = 'Preencha este campo'
    }
    else{
        faixaetaria_error.innerHTML = ''
    }

    if(abordagem.value === 'selecione' || abordagem.value === null)
    {
        e.preventDefault()
       abordagem_error.innerHTML = 'Preencha este campo'
    }
    else{
        abordagem_error.innerHTML = ''
    }

    //Redeclarar pa, se não o else nunca funcionaria, estaria sempre null
    let pa = document.querySelector('input[name="prontoatendimento"]:checked')

    if(!pa)
    {
        e.preventDefault()
       pa_error.innerHTML = 'Preencha este campo'
    }
    else{
        pa_error.innerHTML = ''
    }



    //Depois de preenchida, prevenir atualização da página
    e.preventDefault()
    console.log("SUBMITTED")


   //Aqui pegamos os dados do formulário e enviamos para um servidor por meio do JSON. porém no futuro o objetivo é retornar a lista de instituições, ou seja, criar e filtrar uma lista.
    const formData = new FormData(myForm)
    const data = Object.fromEntries(formData)

    //Utilizamos um site do qual você pode extrair e enviar dados para teste, criando assim uma espécie de dicionário com os dados inseridos (ver console) 
    fetch('https://reqres.in/api/users', {
        method: 'POST',
        headers: {
            'x-api-key': 'reqres-free-v1',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    }).then(res=> res.json())
        .then(data => console.log(data))
        .catch(error => console.log(error))


})


