//A partir da escolha do estado, a drop down list aparece com os municípios correspondentes

function mudaEstado(x){
    //lista de municípios
    let municipios_por_estado = [
       ["MG","Abadia dos Dourados"],	
        ["MG","Abaete"],	
        ["MG","Abre Campo"],	
        ["MG","Acaiaca"],	
        ["MG","Acucena"],	
        ["MG","Agua Boa"],	
        ["MG","Agua Comprida"],	
        ["MG","Aguanil"],	
        ["MG","Aguas Formosas"],	
        ["MG","Aguas Vermelhas"],	
        ["MG","Aimores"],	
        ["MG","Aiuruoca"],	
        ["MG","Alagoa"],	
        ["MG","Albertina"],	
        ["MG","Alem Paraiba"],	
        ["MG","Alfenas"],	
        ["MG","Alfredo Vasconcelos"],	
        ["MG","Almenara"],	
        ["MG","Alpercata"],	
        ["MG","Alpinopolis"],	
        ["MG","Alterosa"],	
        ["MG","Alto Caparao"],	
        ["MG","Alto Jequitiba"],	
        ["MG","Alto Rio Doce"],	
        ["MG","Alvarenga"],	
        ["MG","Alvinopolis"],	
        ["MG","Alvorada de Minas"],	
        ["MG","Amparo do Serra"],	
        ["MG","Andradas"],	
        ["MG","Andrelandia"],	
        ["MG","Angelandia"],	
        ["MG","Antonio Carlos"],	
        ["MG","Antonio Dias"],	
        ["MG","Antonio Prado de Minas"],	
        ["MG","Aracai"],	
        ["MG","Aracitaba"],	
        ["MG","Aracuai"],	
        ["MG","Araguari"],	
        ["MG","Arantina"],	
        ["MG","Araponga"],	
        ["MG","Arapora"],	
        ["MG","Arapua"],	
        ["MG","Araujos"],	
        ["MG","Araxa"],	
        ["MG","Arceburgo"],	
        ["MG","Arcos"],	
        ["MG","Areado"],	
        ["MG","Argirita"],	
        ["MG","Aricanduva"],	
        ["MG","Arinos"],	
        ["MG","Astolfo Dutra"],	
        ["MG","Ataleia"],	
        ["MG","Augusto de Lima"],	
        ["MG","Baependi"],	
        ["MG","Baldim"],	
        ["MG","Bambui"],	
        ["MG","Bandeira do Sul"],	
        ["MG","Bandeira"],	
        ["MG","Barao de Cocais"],	
        ["MG","Barao de Monte Alto"],	
        ["MG","Barbacena"],	
        ["MG","Barra Longa"],	
        ["MG","Barroso"],	
        ["MG","Bela Vista de Minas"],	
        ["MG","Belmiro Braga"],	
        ["MG","Belo Horizonte"],	
        ["MG","Belo Oriente"],	
        ["MG","Belo Vale"],	
        ["MG","Berilo"],	
        ["MG","Berizal"],	
        ["MG","Bertopolis"],	
        ["MG","Betim"],	
        ["MG","Bias Fortes"],	
        ["MG","Bicas"],	
        ["MG","Biquinhas"],	
        ["MG","Boa Esperanca"],	
        ["MG","Bocaina de Minas"],	
        ["MG","Bocaiuva"],	
        ["MG","Bom Despacho"],	
        ["MG","Bom Jardim de Minas"],	
        ["MG","Bom Jesus da Penha"],	
        ["MG","Bom Jesus do Amparo"],	
        ["MG","Bom Jesus do Galho"],	
        ["MG","Bom Repouso"],	
        ["MG","Bom Sucesso"],	
        ["MG","Bonfim"],	
        ["MG","Bonfinopolis de Minas"],	
        ["MG","Bonito de Minas"],	
        ["MG","Borda da Mata"],	
        ["MG","Botelhos"],	
        ["MG","Botumirim"],	
        ["MG","Bras Pires"],	
        ["MG","Brasilandia de Minas"],	
        ["MG","Brasilia de Minas"],	
        ["MG","Brasopolis"],	
        ["MG","Braunas"],	
        ["MG","Brumadinho"],	
        ["MG","Bueno Brandao"],	
        ["MG","Buenopolis"],	
        ["MG","Bugre"],	
        ["MG","Buritis"],	
        ["MG","Buritizeiro"],	
        ["MG","Cabeceira Grande"],	
        ["MG","Cabo Verde"],	
        ["MG","Cachoeira Dourada"],	
        ["MG","Cachoeira da Prata"],	
        ["MG","Cachoeira de Minas"],	
        ["MG","Cachoeira de Pajeu"],	
        ["MG","Caetanopolis"],	
        ["MG","Caete"],	
        ["MG","Caiana"],	
        ["MG","Cajuri"],	
        ["MG","Caldas"],	
        ["MG","Camacho"],	
        ["MG","Camanducaia"],	
        ["MG","Cambui"],	
        ["MG","Cambuquira"],	
        ["MG","Campanario"],	
        ["MG","Campanha"],	
        ["MG","Campestre"],	
        ["MG","Campina Verde"],	
        ["MG","Campo Azul"],	
        ["MG","Campo Belo"],	
        ["MG","Campo Florido"],	
        ["MG","Campo do Meio"],	
        ["MG","Campos Altos"],	
        ["MG","Campos Gerais"],	
        ["MG","Cana Verde"],	
        ["MG","Canaa"],	
        ["MG","Canapolis"],	
        ["MG","Candeias"],	
        ["MG","Cantagalo"],	
        ["MG","Caparao"],	
        ["MG","Capela Nova"],	
        ["MG","Capelinha"],	
        ["MG","Capetinga"],	
        ["MG","Capim Branco"],	
        ["MG","Capinopolis"],	
        ["MG","Capitao Andrade"],	
        ["MG","Capitao Eneas"],	
        ["MG","Capitolio"],	
        ["MG","Caputira"],	
        ["MG","Carai"],	
        ["MG","Caranaiba"],	
        ["MG","Carandai"],	
        ["MG","Carangola"],	
        ["MG","Caratinga"],	
        ["MG","Carbonita"],	
        ["MG","Careacu"],	
        ["MG","Carlos Chagas"],	
        ["MG","Carmesia"],	
        ["MG","Carmo da Cachoeira"],	
        ["MG","Carmo da Mata"],	
        ["MG","Carmo de Minas"],	
        ["MG","Carmo do Cajuru"],	
        ["MG","Carmo do Paranaiba"],	
        ["MG","Carmo do Rio Claro"],	
        ["MG","Carmopolis de Minas"],	
        ["MG","Carneirinho"],	
        ["MG","Carrancas"],	
        ["MG","Carvalhopolis"],	
        ["MG","Carvalhos"],	
        ["MG","Casa Grande"],	
        ["MG","Cascalho Rico"],	
        ["MG","Cassia"],	
        ["MG","Cataguases"],	
        ["MG","Catas Altas da Noruega"],	
        ["MG","Catas Altas"],	
        ["MG","Catuji"],	
        ["MG","Catuti"],	
        ["MG","Caxambu"],	
        ["MG","Cedro do Abaete"],	
        ["MG","Central de Minas"],	
        ["MG","Centralina"],	
        ["MG","Chacara"],	
        ["MG","Chale"],	
        ["MG","Chapada Gaucha"],	
        ["MG","Chapada do Norte"],	
        ["MG","Chiador"],	
        ["MG","Cipotanea"],	
        ["MG","Claraval"],	
        ["MG","Claro dos Pocoes"],	
        ["MG","Claudio"],	
        ["MG","Coimbra"],	
        ["MG","Coluna"],	
        ["MG","Comendador Gomes"],	
        ["MG","Comercinho"],	
        ["MG","Conceicao da Aparecida"],	
        ["MG","Conceicao da Barra de Minas"],	
        ["MG","Conceicao das Alagoas"],	
        ["MG","Conceicao das Pedras"],	
        ["MG","Conceicao de Ipanema"],	
        ["MG","Conceicao do Mato Dentro"],	
        ["MG","Conceicao do Para"],	
        ["MG","Conceicao do Rio Verde"],	
        ["MG","Conceicao dos Ouros"],	
        ["MG","Conego Marinho"],	
        ["MG","Confins"],	
        ["MG","Congonhal"],	
        ["MG","Congonhas do Norte"],	
        ["MG","Congonhas"],	
        ["MG","Conquista"],	
        ["MG","Conselheiro Lafaiete"],	
        ["MG","Conselheiro Pena"],	
        ["MG","Consolacao"],	
        ["MG","Contagem"],	
        ["MG","Coqueiral"],	
        ["MG","Coracao de Jesus"],	
        ["MG","Cordisburgo"],	
        ["MG","Cordislandia"],	
        ["MG","Corinto"],	
        ["MG","Coroaci"],	
        ["MG","Coromandel"],	
        ["MG","Coronel Fabriciano"],	
        ["MG","Coronel Murta"],	
        ["MG","Coronel Pacheco"],	
        ["MG","Coronel Xavier Chaves"],	
        ["MG","Corrego Danta"],	
        ["MG","Corrego Fundo"],	
        ["MG","Corrego Novo"],	
        ["MG","Corrego do Bom Jesus"],	
        ["MG","Couto de Magalhaes de Minas"],	
        ["MG","Crisolita"],	
        ["MG","Cristais"],	
        ["MG","Cristalia"],	
        ["MG","Cristiano Otoni"],	
        ["MG","Cristina"],	
        ["MG","Crucilandia"],	
        ["MG","Cruzeiro da Fortaleza"],	
        ["MG","Cruzilia"],	
        ["MG","Cuparaque"],	
        ["MG","Curral de Dentro"],	
        ["MG","Curvelo"],	
        ["MG","Datas"],	
        ["MG","Delfim Moreira"],	
        ["MG","Delfinopolis"],	
        ["MG","Delta"],	
        ["MG","Descoberto"],	
        ["MG","Desterro de Entre Rios"],	
        ["MG","Desterro do Melo"],	
        ["MG","Diamantina"],	
        ["MG","Diogo de Vasconcelos"],	
        ["MG","Dionisio"],	
        ["MG","Divinesia"],	
        ["MG","Divino das Laranjeiras"],	
        ["MG","Divino"],	
        ["MG","Divinolandia de Minas"],	
        ["MG","Divinopolis"],	
        ["MG","Divisa Alegre"],	
        ["MG","Divisa Nova"],	
        ["MG","Divisopolis"],	
        ["MG","Dom Bosco"],	
        ["MG","Dom Cavati"],	
        ["MG","Dom Joaquim"],	
        ["MG","Dom Silverio"],	
        ["MG","Dom Vicoso"],	
        ["MG","Dona Euzebia"],	
        ["MG","Dores de Campos"],	
        ["MG","Dores de Guanhaes"],	
        ["MG","Dores do Indaia"],	
        ["MG","Dores do Turvo"],	
        ["MG","Doresopolis"],	
        ["MG","Douradoquara"],	
        ["MG","Durande"],	
        ["MG","Eloi Mendes"],	
        ["MG","Engenheiro Caldas"],	
        ["MG","Engenheiro Navarro"],	
        ["MG","Entre Folhas"],	
        ["MG","Entre Rios de Minas"],	
        ["MG","Ervalia"],	
        ["MG","Esmeraldas"],	
        ["MG","Espera Feliz"],	
        ["MG","Espinosa"],	
        ["MG","Espirito Santo do Dourado"],	
        ["MG","Estiva"],	
        ["MG","Estrela Dalva"],	
        ["MG","Estrela do Indaia"],	
        ["MG","Estrela do Sul"],	
        ["MG","Eugenopolis"],	
        ["MG","Ewbank da Camara"],	
        ["MG","Extrema"],	
        ["MG","Fama"],	
        ["MG","Faria Lemos"],	
        ["MG","Felicio dos Santos"],	
        ["MG","Felisburgo"],	
        ["MG","Felixlandia"],	
        ["MG","Fernandes Tourinho"],	
        ["MG","Ferros"],	
        ["MG","Fervedouro"],	
        ["MG","Florestal"],	
        ["MG","Formiga"],	
        ["MG","Formoso"],	
        ["MG","Fortaleza de Minas"],	
        ["MG","Fortuna de Minas"],	
        ["MG","Francisco Badaro"],	
        ["MG","Francisco Dumont"],	
        ["MG","Francisco Sa"],	
        ["MG","Franciscopolis"],	
        ["MG","Frei Gaspar"],	
        ["MG","Frei Inocencio"],	
        ["MG","Frei Lagonegro"],	
        ["MG","Fronteira dos Vales"],	
        ["MG","Fronteira"],	
        ["MG","Fruta de Leite"],	
        ["MG","Frutal"],	
        ["MG","Funilandia"],	
        ["MG","Galileia"],	
        ["MG","Gameleiras"],	
        ["MG","Glaucilandia"],	
        ["MG","Goiabeira"],	
        ["MG","Goiana"],	
        ["MG","Goncalves"],	
        ["MG","Gonzaga"],	
        ["MG","Gouvea"],	
        ["MG","Governador Valadares"],	
        ["MG","Grao Mogol"],	
        ["MG","Grupiara"],	
        ["MG","Guanhaes"],	
        ["MG","Guape"],	
        ["MG","Guaraciaba"],	
        ["MG","Guaraciama"],	
        ["MG","Guaranesia"],	
        ["MG","Guarani"],	
        ["MG","Guarara"],	
        ["MG","Guarda-Mor"],	
        ["MG","Guaxupe"],	
        ["MG","Guidoval"],	
        ["MG","Guimarania"],	
        ["MG","Guiricema"],	
        ["MG","Gurinhata"],	
        ["MG","Heliodora"],	
        ["MG","Iapu"],	
        ["MG","Ibertioga"],	
        ["MG","Ibia"],	
        ["MG","Ibiai"],	
        ["MG","Ibiracatu"],	
        ["MG","Ibiraci"],	
        ["MG","Ibirite"],	
        ["MG","Ibitiura de Minas"],	
        ["MG","Ibituruna"],	
        ["MG","Icarai de Minas"],	
        ["MG","Igarape"],	
        ["MG","Igaratinga"],	
        ["MG","Iguatama"],	
        ["MG","Ijaci"],	
        ["MG","Ilicinea"],	
        ["MG","Imbe de Minas"],	
        ["MG","Inconfidentes"],	
        ["MG","Indaiabira"],	
        ["MG","Indianopolis"],	
        ["MG","Ingai"],	
        ["MG","Inhapim"],	
        ["MG","Inhauma"],	
        ["MG","Inimutaba"],	
        ["MG","Ipaba"],	
        ["MG","Ipanema"],	
        ["MG","Ipatinga"],	
        ["MG","Ipiacu"],	
        ["MG","Ipuiuna"],	
        ["MG","Irai de Minas"],	
        ["MG","Itabira"],	
        ["MG","Itabirinha de Mantena"],	
        ["MG","Itabirito"],	
        ["MG","Itacambira"],	
        ["MG","Itacarambi"],	
        ["MG","Itaguara"],	
        ["MG","Itaipe"],	
        ["MG","Itajuba"],	
        ["MG","Itamarandiba"],	
        ["MG","Itamarati de Minas"],	
        ["MG","Itambacuri"],	
        ["MG","Itambe do Mato Dentro"],	
        ["MG","Itamogi"],	
        ["MG","Itamonte"],	
        ["MG","Itanhandu"],	
        ["MG","Itanhomi"],	
        ["MG","Itaobim"],	
        ["MG","Itapagipe"],	
        ["MG","Itapecerica"],	
        ["MG","Itapeva"],	
        ["MG","Itatiaiucu"],	
        ["MG","Itau de Minas"],	
        ["MG","Itauna"],	
        ["MG","Itaverava"],	
        ["MG","Itinga"],	
        ["MG","Itueta"],	
        ["MG","Ituiutaba"],	
        ["MG","Itumirim"],	
        ["MG","Iturama"],	
        ["MG","Itutinga"],	
        ["MG","Jaboticatubas"],	
        ["MG","Jacinto"],	
        ["MG","Jacui"],	
        ["MG","Jacutinga"],	
        ["MG","Jaguaracu"],	
        ["MG","Jaiba"],	
        ["MG","Jampruca"],	
        ["MG","Janauba"],	
        ["MG","Januaria"],	
        ["MG","Japaraiba"],	
        ["MG","Japonvar"],	
        ["MG","Jeceaba"],	
        ["MG","Jenipapo de Minas"],	
        ["MG","Jequeri"],	
        ["MG","Jequitai"],	
        ["MG","Jequitiba"],	
        ["MG","Jequitinhonha"],	
        ["MG","Jesuania"],	
        ["MG","Joaima"],	
        ["MG","Joanesia"],	
        ["MG","Joao Monlevade"],	
        ["MG","Joao Pinheiro"],	
        ["MG","Joaquim Felicio"],	
        ["MG","Jordania"],	
        ["MG","Jose Goncalves de Minas"],	
        ["MG","Jose Raydan"],	
        ["MG","Josenopolis"],	
        ["MG","Juatuba"],	
        ["MG","Juiz de Fora"],	
        ["MG","Juramento"],	
        ["MG","Juruaia"],	
        ["MG","Juvenilia"],	
        ["MG","Ladainha"],	
        ["MG","Lagamar"],	
        ["MG","Lagoa Dourada"],	
        ["MG","Lagoa Formosa"],	
        ["MG","Lagoa Grande"],	
        ["MG","Lagoa Santa"],	
        ["MG","Lagoa da Prata"],	
        ["MG","Lagoa dos Patos"],	
        ["MG","Lagoas"],	
        ["MG","Lajinha"],	
        ["MG","Lambari"],	
        ["MG","Lamim"],	
        ["MG","Laranjal"],	
        ["MG","Lassance"],	
        ["MG","Lavras"],	
        ["MG","Leandro Ferreira"],	
        ["MG","Leme do Prado"],	
        ["MG","Leopoldina"],	
        ["MG","Liberdade"],	
        ["MG","Lima Duarte"],	
        ["MG","Limeira do Oeste"],	
        ["MG","Lontra"],	
        ["MG","Luisburgo"],	
        ["MG","Luislandia"],	
        ["MG","Luminarias"],	
        ["MG","Luz"],	
        ["MG","Machacalis"],	
        ["MG","Machado"],	
        ["MG","Madre de Deus de Minas"],	
        ["MG","Malacacheta"],	
        ["MG","Mamonas"],	
        ["MG","Manga"],	
        ["MG","Manhuacu"],	
        ["MG","Manhumirim"],	
        ["MG","Mantena"],	
        ["MG","Mar de Espanha"],	
        ["MG","Maravilhas"],	
        ["MG","Maria da Fe"],	
        ["MG","Mariana"],	
        ["MG","Marilac"],	
        ["MG","Mario Campos"],	
        ["MG","Maripa de Minas"],	
        ["MG","Marlieria"],	
        ["MG","Marmelopolis"],	
        ["MG","Martinho Campos"],	
        ["MG","Martins Soares"],	
        ["MG","Mata Verde"],	
        ["MG","Materlandia"],	
        ["MG","Mateus Leme"],	
        ["MG","Mathias Lobato"],	
        ["MG","Matias Barbosa"],	
        ["MG","Matias Cardoso"],	
        ["MG","Matipo"],	
        ["MG","Mato Verde"],	
        ["MG","Matozinhos"],	
        ["MG","Matutina"],	
        ["MG","Medeiros"],	
        ["MG","Medina"],	
        ["MG","Mendes Pimentel"],	
        ["MG","Merces"],	
        ["MG","Mesquita"],	
        ["MG","Minas Novas"],	
        ["MG","Minduri"],	
        ["MG","Mirabela"],	
        ["MG","Miradouro"],	
        ["MG","Mirai"],	
        ["MG","Miravania"],	
        ["MG","Moeda"],	
        ["MG","Moema"],	
        ["MG","Monjolos"],	
        ["MG","Monsenhor Paulo"],	
        ["MG","Montalvania"],	
        ["MG","Monte Alegre de Minas"],	
        ["MG","Monte Azul"],	
        ["MG","Monte Belo"],	
        ["MG","Monte Carmelo"],	
        ["MG","Monte Formoso"],	
        ["MG","Monte Santo de Minas"],	
        ["MG","Monte Siao"],	
        ["MG","Montes Claros"],	
        ["MG","Montezuma"],	
        ["MG","Morada Nova de Minas"],	
        ["MG","Morro da Garca"],	
        ["MG","Morro do Pilar"],	
        ["MG","Munhoz"],	
        ["MG","Muriae"],	
        ["MG","Mutum"],	
        ["MG","Muzambinho"],	
        ["MG","Nacip Raydan"],	
        ["MG","Nanuque"],	
        ["MG","Naque"],	
        ["MG","Natalandia"],	
        ["MG","Natercia"],	
        ["MG","Nazareno"],	
        ["MG","Nepomuceno"],	
        ["MG","Ninheira"],	
        ["MG","Nova Belem"],	
        ["MG","Nova Era"],	
        ["MG","Nova Lima"],	
        ["MG","Nova Modica"],	
        ["MG","Nova Ponte"],	
        ["MG","Nova Porteirinha"],	
        ["MG","Nova Resende"],	
        ["MG","Nova Serrana"],	
        ["MG","Nova Uniao"],	
        ["MG","Novo Cruzeiro"],	
        ["MG","Novo Oriente de Minas"],	
        ["MG","Novorizonte"],	
        ["MG","Olaria"],	
        ["MG","Olhos-d'Agua"],	
        ["MG","Olimpio Noronha"],	
        ["MG","Oliveira Fortes"],	
        ["MG","Oliveira"],	
        ["MG","Onca de Pitangui"],	
        ["MG","Oratorios"],	
        ["MG","Orizania"],	
        ["MG","Ouro Branco"],	
        ["MG","Ouro Fino"],	
        ["MG","Ouro Preto"],	
        ["MG","Ouro Verde de Minas"],	
        ["MG","Padre Carvalho"],	
        ["MG","Padre Paraiso"],	
        ["MG","Pai Pedro"],	
        ["MG","Paineiras"],	
        ["MG","Pains"],	
        ["MG","Paiva"],	
        ["MG","Palma"],	
        ["MG","Palmopolis"],	
        ["MG","Papagaios"],	
        ["MG","Para de Minas"],	
        ["MG","Paracatu"],	
        ["MG","Paraguacu"],	
        ["MG","Paraisopolis"],	
        ["MG","Paraopeba"],	
        ["MG","Passa Quatro"],	
        ["MG","Passa Tempo"],	
        ["MG","Passa Vinte"],	
        ["MG","Passabem"],	
        ["MG","Passos"],	
        ["MG","Patis"],	
        ["MG","Patos de Minas"],	
        ["MG","Patrocinio do Muriae"],	
        ["MG","Patrocinio"],	
        ["MG","Paula Candido"],	
        ["MG","Paulistas"],	
        ["MG","Pavao"],	
        ["MG","Pecanha"],	
        ["MG","Pedra Azul"],	
        ["MG","Pedra Bonita"],	
        ["MG","Pedra Dourada"],	
        ["MG","Pedra do Anta"],	
        ["MG","Pedra do Indaia"],	
        ["MG","Pedralva"],	
        ["MG","Pedras de Maria da Cruz"],	
        ["MG","Pedrinopolis"],	
        ["MG","Pedro Leopoldo"],	
        ["MG","Pedro Teixeira"],	
        ["MG","Pequeri"],	
        ["MG","Pequi"],	
        ["MG","Perdigao"],	
        ["MG","Perdizes"],	
        ["MG","Perdoes"],	
        ["MG","Periquito"],	
        ["MG","Pescador"],	
        ["MG","Piau"],	
        ["MG","Piedade de Caratinga"],	
        ["MG","Piedade de Ponte Nova"],	
        ["MG","Piedade do Rio Grande"],	
        ["MG","Piedade dos Gerais"],	
        ["MG","Pimenta"],	
        ["MG","Pingo d'Agua"],	
        ["MG","Pintopolis"],	
        ["MG","Piracema"],	
        ["MG","Pirajuba"],	
        ["MG","Piranga"],	
        ["MG","Pirangucu"],	
        ["MG","Piranguinho"],	
        ["MG","Pirapetinga"],	
        ["MG","Pirapora"],	
        ["MG","Pirauba"],	
        ["MG","Pitangui"],	
        ["MG","Piui"],	
        ["MG","Planura"],	
        ["MG","Poco Fundo"],	
        ["MG","Pocos de Caldas"],	
        ["MG","Pocrane"],	
        ["MG","Pompeu"],	
        ["MG","Ponte Nova"],	
        ["MG","Ponto Chique"],	
        ["MG","Ponto dos Volantes"],	
        ["MG","Porteirinha"],	
        ["MG","Porto Firme"],	
        ["MG","Pote"],	
        ["MG","Pouso Alegre"],	
        ["MG","Pouso Alto"],	
        ["MG","Prados"],	
        ["MG","Prata"],	
        ["MG","Pratapolis"],	
        ["MG","Pratinha"],	
        ["MG","Presidente Bernardes"],	
        ["MG","Presidente Juscelino"],	
        ["MG","Presidente Kubitschek"],	
        ["MG","Presidente Olegario"],	
        ["MG","Prudente de Morais"],	
        ["MG","Quartel Geral"],	
        ["MG","Queluzita"],	
        ["MG","Raposos"],	
        ["MG","Raul Soares"],	
        ["MG","Recreio"],	
        ["MG","Reduto"],	
        ["MG","Resende Costa"],	
        ["MG","Resplendor"],	
        ["MG","Ressaquinha"],	
        ["MG","Riachinho"],	
        ["MG","Riacho dos Machados"],	
        ["MG","Ribeirao Vermelho"],	
        ["MG","Ribeirao das Neves"],	
        ["MG","Rio Acima"],	
        ["MG","Rio Casca"],	
        ["MG","Rio Doce"],	
        ["MG","Rio Espera"],	
        ["MG","Rio Manso"],	
        ["MG","Rio Novo"],	
        ["MG","Rio Paranaiba"],	
        ["MG","Rio Pardo de Minas"],	
        ["MG","Rio Piracicaba"],	
        ["MG","Rio Pomba"],	
        ["MG","Rio Preto"],	
        ["MG","Rio Vermelho"],	
        ["MG","Rio do Prado"],	
        ["MG","Ritapolis"],	
        ["MG","Rochedo de Minas"],	
        ["MG","Rodeiro"],	
        ["MG","Romaria"],	
        ["MG","Rosario da Limeira"],	
        ["MG","Rubelita"],	
        ["MG","Rubim"],	
        ["MG","Sabara"],	
        ["MG","Sabinopolis"],	
        ["MG","Sacramento"],	
        ["MG","Salinas"],	
        ["MG","Salto da Divisa"],	
        ["MG","Santa Barbara do Leste"],	
        ["MG","Santa Barbara do Monte Verde"],	
        ["MG","Santa Barbara do Tugurio"],	
        ["MG","Santa Barbara"],	
        ["MG","Santa Cruz de Minas"],	
        ["MG","Santa Cruz de Salinas"],	
        ["MG","Santa Cruz do Escalvado"],	
        ["MG","Santa Efigenia de Minas"],	
        ["MG","Santa Fe de Minas"],	
        ["MG","Santa Helena de Minas"],	
        ["MG","Santa Juliana"],	
        ["MG","Santa Luzia"],	
        ["MG","Santa Margarida"],	
        ["MG","Santa Maria de Itabira"],	
        ["MG","Santa Maria do Salto"],	
        ["MG","Santa Maria do Suacui"],	
        ["MG","Santa Rita de Caldas"],	
        ["MG","Santa Rita de Ibitipoca"],	
        ["MG","Santa Rita de Jacutinga"],	
        ["MG","Santa Rita de Minas"],	
        ["MG","Santa Rita do Itueto"],	
        ["MG","Santa Rita do Sapucai"],	
        ["MG","Santa Rosa da Serra"],	
        ["MG","Santa Vitoria"],	
        ["MG","Santana da Vargem"],	
        ["MG","Santana de Cataguases"],	
        ["MG","Santana de Pirapama"],	
        ["MG","Santana do Deserto"],	
        ["MG","Santana do Garambeu"],	
        ["MG","Santana do Jacare"],	
        ["MG","Santana do Manhuacu"],	
        ["MG","Santana do Paraiso"],	
        ["MG","Santana do Riacho"],	
        ["MG","Santana dos Montes"],	
        ["MG","Santo Antonio do Amparo"],	
        ["MG","Santo Antonio do Aventureiro"],	
        ["MG","Santo Antonio do Grama"],	
        ["MG","Santo Antonio do Itambe"],	
        ["MG","Santo Antonio do Jacinto"],	
        ["MG","Santo Antonio do Monte"],	
        ["MG","Santo Antonio do Retiro"],	
        ["MG","Santo Antonio do Rio Abaixo"],	
        ["MG","Santo Hipolito"],	
        ["MG","Santos Dumont"],	
        ["MG","Sao Bento Abade"],	
        ["MG","Sao Bras do Suacui"],	
        ["MG","Sao Domingos das Dores"],	
        ["MG","Sao Domingos do Prata"],	
        ["MG","Sao Felix de Minas"],	
        ["MG","Sao Francisco de Paula"],	
        ["MG","Sao Francisco de Sales"],	
        ["MG","Sao Francisco do Gloria"],	
        ["MG","Sao Francisco"],	
        ["MG","Sao Geraldo da Piedade"],	
        ["MG","Sao Geraldo do Baixio"],	
        ["MG","Sao Geraldo"],	
        ["MG","Sao Goncalo do Abaete"],	
        ["MG","Sao Goncalo do Para"],	
        ["MG","Sao Goncalo do Rio Abaixo"],	
        ["MG","Sao Goncalo do Rio Preto"],	
        ["MG","Sao Goncalo do Sapucai"],	
        ["MG","Sao Gotardo"],	
        ["MG","Sao Joao Batista do Gloria"],	
        ["MG","Sao Joao Evangelista"],	
        ["MG","Sao Joao Nepomuceno"],	
        ["MG","Sao Joao da Lagoa"],	
        ["MG","Sao Joao da Mata"],	
        ["MG","Sao Joao da Ponte"],	
        ["MG","Sao Joao das Missoes"],	
        ["MG","Sao Joao del Rei"],	
        ["MG","Sao Joao do Manhuacu"],	
        ["MG","Sao Joao do Manteninha"],	
        ["MG","Sao Joao do Oriente"],	
        ["MG","Sao Joao do Pacui"],	
        ["MG","Sao Joao do Paraiso"],	
        ["MG","Sao Joaquim de Bicas"],	
        ["MG","Sao Jose da Barra"],	
        ["MG","Sao Jose da Lapa"],	
        ["MG","Sao Jose da Safira"],	
        ["MG","Sao Jose da Varginha"],	
        ["MG","Sao Jose do Alegre"],	
        ["MG","Sao Jose do Divino"],	
        ["MG","Sao Jose do Goiabal"],	
        ["MG","Sao Jose do Jacuri"],	
        ["MG","Sao Jose do Mantimento"],	
        ["MG","Sao Lourenco"],	
        ["MG","Sao Miguel do Anta"],	
        ["MG","Sao Pedro da Uniao"],	
        ["MG","Sao Pedro do Suacui"],	
        ["MG","Sao Pedro dos Ferros"],	
        ["MG","Sao Romao"],	
        ["MG","Sao Roque de Minas"],	
        ["MG","Sao Sebastiao da Bela Vista"],	
        ["MG","Sao Sebastiao da Vargem Alegre"],	
        ["MG","Sao Sebastiao do Anta"],	
        ["MG","Sao Sebastiao do Maranhao"],	
        ["MG","Sao Sebastiao do Oeste"],	
        ["MG","Sao Sebastiao do Paraiso"],	
        ["MG","Sao Sebastiao do Rio Preto"],	
        ["MG","Sao Sebastiao do Rio Verde"],	
        ["MG","Sao Thome das Letras"],	
        ["MG","Sao Tiago"],	
        ["MG","Sao Tomas de Aquino"],	
        ["MG","Sao Vicente de Minas"],	
        ["MG","Sapucai-Mirim"],	
        ["MG","Sardoa"],	
        ["MG","Sarzedo"],	
        ["MG","Sem-Peixe"],	
        ["MG","Senador Amaral"],	
        ["MG","Senador Cortes"],	
        ["MG","Senador Firmino"],	
        ["MG","Senador Jose Bento"],	
        ["MG","Senador Modestino Goncalves"],	
        ["MG","Senhora de Oliveira"],	
        ["MG","Senhora do Porto"],	
        ["MG","Senhora dos Remedios"],	
        ["MG","Sericita"],	
        ["MG","Seritinga"],	
        ["MG","Serra Azul de Minas"],	
        ["MG","Serra da Saudade"],	
        ["MG","Serra do Salitre"],	
        ["MG","Serra dos Aimores"],	
        ["MG","Serrania"],	
        ["MG","Serranopolis de Minas"],	
        ["MG","Serranos"],	
        ["MG","Serro"],	
        ["MG","Sete Lagoas"],	
        ["MG","Setubinha"],	
        ["MG","Silveirania"],	
        ["MG","Silvianopolis"],	
        ["MG","Simao Pereira"],	
        ["MG","Simonesia"],	
        ["MG","Sobralia"],	
        ["MG","Soledade de Minas"],	
        ["MG","Tabuleiro"],	
        ["MG","Taiobeiras"],	
        ["MG","Taparuba"],	
        ["MG","Tapira"],	
        ["MG","Tapirai"],	
        ["MG","Taquaracu de Minas"],	
        ["MG","Tarumirim"],	
        ["MG","Teixeiras"],	
        ["MG","Teofilo Otoni"],	
        ["MG","Timoteo"],	
        ["MG","Tiradentes"],	
        ["MG","Tiros"],	
        ["MG","Tocantins"],	
        ["MG","Tocos do Moji"],	
        ["MG","Toledo"],	
        ["MG","Tombos"],	
        ["MG","Tres Coracoes"],	
        ["MG","Tres Marias"],	
        ["MG","Tres Pontas"],	
        ["MG","Tumiritinga"],	
        ["MG","Tupaciguara"],	
        ["MG","Turmalina"],	
        ["MG","Turvolandia"],	
        ["MG","Uba"],	
        ["MG","Ubai"],	
        ["MG","Ubaporanga"],	
        ["MG","Uberaba"],	
        ["MG","Uberlandia"],	
        ["MG","Umburatiba"],	
        ["MG","Unai"],	
        ["MG","Uniao de Minas"],	
        ["MG","Uruana de Minas"],	
        ["MG","Urucania"],	
        ["MG","Urucuia"],	
        ["MG","Vargem Alegre"],	
        ["MG","Vargem Bonita"],	
        ["MG","Vargem Grande do Rio Pardo"],	
        ["MG","Varginha"],	
        ["MG","Varjao de MInas"],	
        ["MG","Varzea da Palma"],	
        ["MG","Varzelandia"],	
        ["MG","Vazante"],	
        ["MG","Verdelandia"],	
        ["MG","Veredinha"],	
        ["MG","Verissimo"],	
        ["MG","Vermelho Novo"],	
        ["MG","Vespasiano"],	
        ["MG","Vicosa"],	
        ["MG","Vieiras"],	
        ["MG","Virgem da Lapa"],	
        ["MG","Virginia"],	
        ["MG","Virginopolis"],	
        ["MG","Virgolandia"],	
        ["MG","Visconde do Rio Branco"],	
        ["MG","Volta Grande"],	
        ["MG","Wenceslau Braz"],	
        ["RJ","Angra dos Reis"],	
        ["RJ","Aperibé"],	
        ["RJ","Araruama"],	
        ["RJ","Areal"],	
        ["RJ","Armação dos Búzios"],	
        ["RJ","Arraial do Cabo"],	
        ["RJ","Barra do Piraí"],	
        ["RJ","Barra Mansa"],	
        ["RJ","Belford Roxo"],	
        ["RJ","Bom Jardim"],	
        ["RJ","Bom Jesus do Itabapoana"],	
        ["RJ","Cabo Frio"],	
        ["RJ","Cachoeiras de Macacu"],	
        ["RJ","Cambuci"],	
        ["RJ","Campos dos Goytacazes"],	
        ["RJ","Cantagalo"],	
        ["RJ","Carapebus"],	
        ["RJ","Cardoso Moreira"],	
        ["RJ","Carmo"],	
        ["RJ","Casimiro de Abreu"],	
        ["RJ","Comendador Levy Gasparian"],	
        ["RJ","Conceição de Macabu"],	
        ["RJ","Cordeiro"],	
        ["RJ","Duas Barras"],	
        ["RJ","Duque de Caxias"],	
        ["RJ","Engenheiro Paulo de Frontin"],	
        ["RJ","Guapimirim"],	
        ["RJ","Iguaba Grande"],	
        ["RJ","Itaboraí"],	
        ["RJ","Itaguaí"],	
        ["RJ","Italva"],	
        ["RJ","Itaocara"],	
        ["RJ","Itaperuna"],	
        ["RJ","Itatiaia"],	
        ["RJ","Japeri"],	
        ["RJ","Laje do Muriaé"],	
        ["RJ","Macaé"],	
        ["RJ","Macuco"],	
        ["RJ","Magé"],	
        ["RJ","Mangaratiba"],	
        ["RJ","Maricá"],	
        ["RJ","Mendes"],	
        ["RJ","Mesquita"],	
        ["RJ","Miguel Pereira"],	
        ["RJ","Miracema"],	
        ["RJ","Natividade"],	
        ["RJ","Nilópolis"],	
        ["RJ","Niterói"],	
        ["RJ","Nova Friburgo"],	
        ["RJ","Nova Iguaçu"],	
        ["RJ","Paracambi"],	
        ["RJ","Paraíba do Sul"],	
        ["RJ","Paraty"],	
        ["RJ","Paty do Alferes"],	
        ["RJ","Petrópolis"],	
        ["RJ","Pinheiral"],	
        ["RJ","Piraí"],	
        ["RJ","Porciúncula"],	
        ["RJ","Porto Real"],	
        ["RJ","Quatis"],	
        ["RJ","Queimados"],	
        ["RJ","Quissamã"],	
        ["RJ","Resende"],	
        ["RJ","Rio Bonito"],	
        ["RJ","Rio Claro"],	
        ["RJ","Rio das Flores"],	
        ["RJ","Rio das Ostras"],	
        ["RJ","Rio de Janeiro"],	
        ["RJ","Santa Maria Madalena"],	
        ["RJ","Santo Antônio de Pádua"],	
        ["RJ","São Fidélis"],	
        ["RJ","São Francisco de Itabapoana"],	
        ["RJ","São Gonçalo"],	
        ["RJ","São João da Barra"],	
        ["RJ","São João de Meriti"],	
        ["RJ","São José de Ubá"],	
        ["RJ","São José do Vale do Rio Preto"],	
        ["RJ","São Pedro da Aldeia"],	
        ["RJ","São Sebastião do Alto"],	
        ["RJ","Sapucaia"],	
        ["RJ","Saquarema"],	
        ["RJ","Seropédica"],	
        ["RJ","Silva Jardim"],	
        ["RJ","Sumidouro"],	
        ["RJ","Tanguá"],	
        ["RJ","Teresópolis"],	
        ["RJ","Trajano de Moraes"],	
        ["RJ","Três Rios"],	
        ["RJ","Valença"],	
        ["RJ","Varre-Sai"],	
        ["RJ","Vassouras"],	
        ["RJ","Volta Redonda"],	
        ["SP","Adamantina"],	
        ["SP","Adolfo"],	
        ["SP","Aguaí"],	
        ["SP","Águas da Prata"],	
        ["SP","Águas de Lindóia"],	
        ["SP","Águas de Santa Bárbara"],	
        ["SP","Águas de São Pedro"],	
        ["SP","Agudos"],	
        ["SP","Alambari"],	
        ["SP","Alfredo Marcondes"],	
        ["SP","Altair"],	
        ["SP","Altinópolis"],	
        ["SP","Alto Alegre"],	
        ["SP","Alumínio"],	
        ["SP","Álvares Florence"],	
        ["SP","Álvares Machado"],	
        ["SP","Álvaro de Carvalho"],	
        ["SP","Alvinlândia"],	
        ["SP","Americana"],	
        ["SP","Américo Brasiliense"],	
        ["SP","Américo de Campos"],	
        ["SP","Amparo"],	
        ["SP","Analândia"],	
        ["SP","Andradina"],	
        ["SP","Angatuba"],	
        ["SP","Anhembi"],	
        ["SP","Anhumas"],	
        ["SP","Aparecida"],	
        ["SP","Aparecida d'Oeste"],	
        ["SP","Apiaí"],	
        ["SP","Araçariguama"],	
        ["SP","Araçatuba"],	
        ["SP","Araçoiaba da Serra"],	
        ["SP","Aramina"],	
        ["SP","Arandu"],	
        ["SP","Arapeí"],	
        ["SP","Araraquara"],	
        ["SP","Araras"],	
        ["SP","Arco-Íris"],	
        ["SP","Arealva"],	
        ["SP","Areias"],	
        ["SP","Areiópolis"],	
        ["SP","Ariranha"],	
        ["SP","Artur Nogueira"],	
        ["SP","Arujá"],	
        ["SP","Aspásia"],	
        ["SP","Assis"],	
        ["SP","Atibaia"],	
        ["SP","Auriflama"],	
        ["SP","Avaí"],	
        ["SP","Avanhandava"],	
        ["SP","Avaré"],	
        ["SP","Bady Bassitt"],	
        ["SP","Balbinos"],	
        ["SP","Bálsamo"],	
        ["SP","Bananal"],	
        ["SP","Barão de Antonina"],	
        ["SP","Barbosa"],	
        ["SP","Bariri"],	
        ["SP","Barra Bonita"],	
        ["SP","Barra do Chapéu"],	
        ["SP","Barra do Turvo"],	
        ["SP","Barretos"],	
        ["SP","Barrinha"],	
        ["SP","Barueri"],	
        ["SP","Bastos"],	
        ["SP","Batatais"],	
        ["SP","Bauru"],	
        ["SP","Bebedouro"],	
        ["SP","Bento de Abreu"],	
        ["SP","Bernardino de Campos"],	
        ["SP","Bertioga"],	
        ["SP","Bilac"],	
        ["SP","Birigui"],	
        ["SP","Biritiba Mirim"],	
        ["SP","Boa Esperança do Sul"],	
        ["SP","Bocaina"],	
        ["SP","Bofete"],	
        ["SP","Boituva"],	
        ["SP","Bom Jesus dos Perdões"],	
        ["SP","Bom Sucesso de Itararé"],	
        ["SP","Borá"],	
        ["SP","Boraceia"],	
        ["SP","Borborema"],	
        ["SP","Borebi"],	
        ["SP","Botucatu"],	
        ["SP","Bragança Paulista"],	
        ["SP","Braúna"],	
        ["SP","Brejo Alegre"],	
        ["SP","Brodowski"],	
        ["SP","Brotas"],	
        ["SP","Buri"],	
        ["SP","Buritama"],	
        ["SP","Buritizal"],	
        ["SP","Cabrália Paulista"],	
        ["SP","Cabreúva"],	
        ["SP","Caçapava"],	
        ["SP","Cachoeira Paulista"],	
        ["SP","Caconde"],	
        ["SP","Cafelândia"],	
        ["SP","Caiabu"],	
        ["SP","Caieiras"],	
        ["SP","Caiuá"],	
        ["SP","Cajamar"],	
        ["SP","Cajati"],	
        ["SP","Cajobi"],	
        ["SP","Cajuru"],	
        ["SP","Campina do Monte Alegre"],	
        ["SP","Campinas"],	
        ["SP","Campo Limpo Paulista"],	
        ["SP","Campos do Jordão"],	
        ["SP","Campos Novos Paulista"],	
        ["SP","Cananéia"],	
        ["SP","Canas"],	
        ["SP","Cândido Mota"],	
        ["SP","Cândido Rodrigues"],	
        ["SP","Canitar"],	
        ["SP","Capão Bonito"],	
        ["SP","Capela do Alto"],	
        ["SP","Capivari"],	
        ["SP","Caraguatatuba"],	
        ["SP","Carapicuíba"],	
        ["SP","Cardoso"],	
        ["SP","Casa Branca"],	
        ["SP","Cássia dos Coqueiros"],	
        ["SP","Castilho"],	
        ["SP","Catanduva"],	
        ["SP","Catiguá"],	
        ["SP","Cedral"],	
        ["SP","Cerqueira César"],	
        ["SP","Cerquilho"],	
        ["SP","Cesário Lange"],	
        ["SP","Charqueada"],	
        ["SP","Chavantes"],	
        ["SP","Clementina"],	
        ["SP","Colina"],	
        ["SP","Colômbia"],	
        ["SP","Conchal"],	
        ["SP","Conchas"],	
        ["SP","Cordeirópolis"],	
        ["SP","Coroados"],	
        ["SP","Coronel Macedo"],	
        ["SP","Corumbataí"],	
        ["SP","Cosmópolis"],	
        ["SP","Cosmorama"],	
        ["SP","Cotia"],	
        ["SP","Cravinhos"],	
        ["SP","Cristais Paulista"],	
        ["SP","Cruzália"],	
        ["SP","Cruzeiro"],	
        ["SP","Cubatão"],	
        ["SP","Cunha"],	
        ["SP","Descalvado"],	
        ["SP","Diadema"],	
        ["SP","Dirce Reis"],	
        ["SP","Divinolândia"],	
        ["SP","Dobrada"],	
        ["SP","Dois Córregos"],	
        ["SP","Dolcinópolis"],	
        ["SP","Dourado"],	
        ["SP","Dracena"],	
        ["SP","Duartina"],	
        ["SP","Dumont"],	
        ["SP","Echaporã"],	
        ["SP","Eldorado"],	
        ["SP","Elias Fausto"],	
        ["SP","Elisiário"],	
        ["SP","Embaúba"],	
        ["SP","Embu das Artes"],	
        ["SP","Embu-Guaçu"],	
        ["SP","Emilianópolis"],	
        ["SP","Engenheiro Coelho"],	
        ["SP","Espírito Santo do Pinhal"],	
        ["SP","Espírito Santo do Turvo"],	
        ["SP","Estiva Gerbi"],	
        ["SP","Estrela d'Oeste"],	
        ["SP","Estrela do Norte"],	
        ["SP","Euclides da Cunha Paulista"],	
        ["SP","Fartura"],	
        ["SP","Fernando Prestes"],	
        ["SP","Fernandópolis"],	
        ["SP","Fernão"],	
        ["SP","Ferraz de Vasconcelos"],	
        ["SP","Flora Rica"],	
        ["SP","Floreal"],	
        ["SP","Flórida Paulista"],	
        ["SP","Florínea"],	
        ["SP","Franca"],	
        ["SP","Francisco Morato"],	
        ["SP","Franco da Rocha"],	
        ["SP","Gabriel Monteiro"],	
        ["SP","Gália"],	
        ["SP","Garça"],	
        ["SP","Gastão Vidigal"],	
        ["SP","Gavião Peixoto"],	
        ["SP","General Salgado"],	
        ["SP","Getulina"],	
        ["SP","Glicério"],	
        ["SP","Guaiçara"],	
        ["SP","Guaimbê"],	
        ["SP","Guaíra"],	
        ["SP","Guapiaçu"],	
        ["SP","Guapiara"],	
        ["SP","Guará"],	
        ["SP","Guaraçaí"],	
        ["SP","Guaraci"],	
        ["SP","Guarani d'Oeste"],	
        ["SP","Guarantã"],	
        ["SP","Guararapes"],	
        ["SP","Guararema"],	
        ["SP","Guaratinguetá"],	
        ["SP","Guareí"],	
        ["SP","Guariba"],	
        ["SP","Guarujá"],	
        ["SP","Guarulhos"],	
        ["SP","Guatapará"],	
        ["SP","Guzolândia"],	
        ["SP","Herculândia"],	
        ["SP","Holambra"],	
        ["SP","Hortolândia"],	
        ["SP","Iacanga"],	
        ["SP","Iacri"],	
        ["SP","Iaras"],	
        ["SP","Ibaté"],	
        ["SP","Ibirá"],	
        ["SP","Ibirarema"],	
        ["SP","Ibitinga"],	
        ["SP","Ibiúna"],	
        ["SP","Icém"],	
        ["SP","Iepê"],	
        ["SP","Igaraçu do Tietê"],	
        ["SP","Igarapava"],	
        ["SP","Igaratá"],	
        ["SP","Iguape"],	
        ["SP","Ilha Comprida"],	
        ["SP","Ilha Solteira"],	
        ["SP","Ilhabela"],	
        ["SP","Indaiatuba"],	
        ["SP","Indiana"],	
        ["SP","Indiaporã"],	
        ["SP","Inúbia Paulista"],	
        ["SP","Ipaussu"],	
        ["SP","Iperó"],	
        ["SP","Ipeúna"],	
        ["SP","Ipiguá"],	
        ["SP","Iporanga"],	
        ["SP","Ipuã"],	
        ["SP","Iracemápolis"],	
        ["SP","Irapuã"],	
        ["SP","Irapuru"],	
        ["SP","Itaberá"],	
        ["SP","Itaí"],	
        ["SP","Itajobi"],	
        ["SP","Itaju"],	
        ["SP","Itanhaém"],	
        ["SP","Itaoca"],	
        ["SP","Itapecerica da Serra"],	
        ["SP","Itapetininga"],	
        ["SP","Itapeva"],	
        ["SP","Itapevi"],	
        ["SP","Itapira"],	
        ["SP","Itapirapuã Paulista"],	
        ["SP","Itápolis"],	
        ["SP","Itaporanga"],	
        ["SP","Itapuí"],	
        ["SP","Itapura"],	
        ["SP","Itaquaquecetuba"],	
        ["SP","Itararé"],	
        ["SP","Itariri"],	
        ["SP","Itatiba"],	
        ["SP","Itatinga"],	
        ["SP","Itirapina"],	
        ["SP","Itirapuã"],	
        ["SP","Itobi"],	
        ["SP","Itu"],	
        ["SP","Itupeva"],	
        ["SP","Ituverava"],	
        ["SP","Jaborandi"],	
        ["SP","Jaboticabal"],	
        ["SP","Jacareí"],	
        ["SP","Jaci"],	
        ["SP","Jacupiranga"],	
        ["SP","Jaguariúna"],	
        ["SP","Jales"],	
        ["SP","Jambeiro"],	
        ["SP","Jandira"],	
        ["SP","Jardinópolis"],	
        ["SP","Jarinu"],	
        ["SP","Jaú"],	
        ["SP","Jeriquara"],	
        ["SP","Joanópolis"],	
        ["SP","João Ramalho"],	
        ["SP","José Bonifácio"],	
        ["SP","Júlio Mesquita"],	
        ["SP","Jumirim"],	
        ["SP","Jundiaí"],	
        ["SP","Junqueirópolis"],	
        ["SP","Juquiá"],	
        ["SP","Juquitiba"],	
        ["SP","Lagoinha"],	
        ["SP","Laranjal Paulista"],	
        ["SP","Lavínia"],	
        ["SP","Lavrinhas"],	
        ["SP","Leme"],	
        ["SP","Lençóis Paulista"],	
        ["SP","Limeira"],	
        ["SP","Lindoia"],	
        ["SP","Lins"],	
        ["SP","Lorena"],	
        ["SP","Lourdes"],	
        ["SP","Louveira"],	
        ["SP","Lucélia"],	
        ["SP","Lucianópolis"],	
        ["SP","Luiz Antônio"],	
        ["SP","Luiziânia"],	
        ["SP","Lupércio"],	
        ["SP","Lutécia"],	
        ["SP","Macatuba"],	
        ["SP","Macaubal"],	
        ["SP","Macedônia"],	
        ["SP","Magda"],	
        ["SP","Mairinque"],	
        ["SP","Mairiporã"],	
        ["SP","Manduri"],	
        ["SP","Marabá Paulista"],	
        ["SP","Maracaí"],	
        ["SP","Marapoama"],	
        ["SP","Mariápolis"],	
        ["SP","Marília"],	
        ["SP","Marinópolis"],	
        ["SP","Martinópolis"],	
        ["SP","Matão"],	
        ["SP","Mauá"],	
        ["SP","Mendonça"],	
        ["SP","Meridiano"],	
        ["SP","Mesópolis"],	
        ["SP","Miguelópolis"],	
        ["SP","Mineiros do Tietê"],	
        ["SP","Mira Estrela"],	
        ["SP","Miracatu"],	
        ["SP","Mirandópolis"],	
        ["SP","Mirante do Paranapanema"],	
        ["SP","Mirassol"],	
        ["SP","Mirassolândia"],	
        ["SP","Mococa"],	
        ["SP","Mogi das Cruzes"],	
        ["SP","Mogi Guaçu"],	
        ["SP","Mogi Mirim"],	
        ["SP","Mombuca"],	
        ["SP","Monções"],	
        ["SP","Mongaguá"],	
        ["SP","Monte Alegre do Sul"],	
        ["SP","Monte Alto"],	
        ["SP","Monte Aprazível"],	
        ["SP","Monte Azul Paulista"],	
        ["SP","Monte Castelo"],	
        ["SP","Monte Mor"],	
        ["SP","Monteiro Lobato"],	
        ["SP","Morro Agudo"],	
        ["SP","Morungaba"],	
        ["SP","Motuca"],	
        ["SP","Murutinga do Sul"],	
        ["SP","Nantes"],	
        ["SP","Narandiba"],	
        ["SP","Natividade da Serra"],	
        ["SP","Nazaré Paulista"],	
        ["SP","Neves Paulista"],	
        ["SP","Nhandeara"],	
        ["SP","Nipoã"],	
        ["SP","Nova Aliança"],	
        ["SP","Nova Campina"],	
        ["SP","Nova Canaã Paulista"],	
        ["SP","Nova Castilho"],	
        ["SP","Nova Europa"],	
        ["SP","Nova Granada"],	
        ["SP","Nova Guataporanga"],	
        ["SP","Nova Independência"],	
        ["SP","Nova Luzitânia"],	
        ["SP","Nova Odessa"],	
        ["SP","Novais"],	
        ["SP","Novo Horizonte"],	
        ["SP","Nuporanga"],	
        ["SP","Ocauçu"],	
        ["SP","Óleo"],	
        ["SP","Olímpia"],	
        ["SP","Onda Verde"],	
        ["SP","Oriente"],	
        ["SP","Orindiúva"],	
        ["SP","Orlândia"],	
        ["SP","Osasco"],	
        ["SP","Oscar Bressane"],	
        ["SP","Osvaldo Cruz"],	
        ["SP","Ourinhos"],	
        ["SP","Ouro Verde"],	
        ["SP","Ouroeste"],	
        ["SP","Pacaembu"],	
        ["SP","Palestina"],	
        ["SP","Palmares Paulista"],	
        ["SP","Palmeira d'Oeste"],	
        ["SP","Palmital"],	
        ["SP","Panorama"],	
        ["SP","Paraguaçu Paulista"],	
        ["SP","Paraibuna"],	
        ["SP","Paraíso"],	
        ["SP","Paranapanema"],	
        ["SP","Paranapuã"],	
        ["SP","Parapuã"],	
        ["SP","Pardinho"],	
        ["SP","Pariquera-Açu"],	
        ["SP","Parisi"],	
        ["SP","Patrocínio Paulista"],	
        ["SP","Paulicéia"],	
        ["SP","Paulínia"],	
        ["SP","Paulistânia"],	
        ["SP","Paulo de Faria"],	
        ["SP","Pederneiras"],	
        ["SP","Pedra Bela"],	
        ["SP","Pedranópolis"],	
        ["SP","Pedregulho"],	
        ["SP","Pedreira"],	
        ["SP","Pedrinhas Paulista"],	
        ["SP","Pedro de Toledo"],	
        ["SP","Penápolis"],	
        ["SP","Pereira Barreto"],	
        ["SP","Pereiras"],	
        ["SP","Peruíbe"],	
        ["SP","Piacatu"],	
        ["SP","Piedade"],	
        ["SP","Pilar do Sul"],	
        ["SP","Pindamonhangaba"],	
        ["SP","Pindorama"],	
        ["SP","Pinhalzinho"],	
        ["SP","Piquerobi"],	
        ["SP","Piquete"],	
        ["SP","Piracaia"],	
        ["SP","Piracicaba"],	
        ["SP","Piraju"],	
        ["SP","Pirajuí"],	
        ["SP","Pirangi"],	
        ["SP","Pirapora do Bom Jesus"],	
        ["SP","Pirapozinho"],	
        ["SP","Pirassununga"],	
        ["SP","Piratininga"],	
        ["SP","Pitangueiras"],	
        ["SP","Planalto"],	
        ["SP","Platina"],	
        ["SP","Poá"],	
        ["SP","Poloni"],	
        ["SP","Pompeia"],	
        ["SP","Pongaí"],	
        ["SP","Pontal"],	
        ["SP","Pontalinda"],	
        ["SP","Pontes Gestal"],	
        ["SP","Populina"],	
        ["SP","Porangaba"],	
        ["SP","Porto Feliz"],	
        ["SP","Porto Ferreira"],	
        ["SP","Potim"],	
        ["SP","Potirendaba"],	
        ["SP","Pracinha"],	
        ["SP","Pradópolis"],	
        ["SP","Praia Grande"],	
        ["SP","Pratânia"],	
        ["SP","Presidente Alves"],	
        ["SP","Presidente Bernardes"],	
        ["SP","Presidente Epitácio"],	
        ["SP","Presidente Prudente"],	
        ["SP","Presidente Venceslau"],	
        ["SP","Promissão"],	
        ["SP","Quadra"],	
        ["SP","Quatá"],	
        ["SP","Queiroz"],	
        ["SP","Queluz"],	
        ["SP","Quintana"],	
        ["SP","Rafard"],	
        ["SP","Rancharia"],	
        ["SP","Redenção da Serra"],	
        ["SP","Regente Feijó"],	
        ["SP","Reginópolis"],	
        ["SP","Registro"],	
        ["SP","Restinga"],	
        ["SP","Ribeira"],	
        ["SP","Ribeirão Bonito"],	
        ["SP","Ribeirão Branco"],	
        ["SP","Ribeirão Corrente"],	
        ["SP","Ribeirão do Sul"],	
        ["SP","Ribeirão dos Índios"],	
        ["SP","Ribeirão Grande"],	
        ["SP","Ribeirão Pires"],	
        ["SP","Ribeirão Preto"],	
        ["SP","Rifaina"],	
        ["SP","Rincão"],	
        ["SP","Rinópolis"],	
        ["SP","Rio Claro"],	
        ["SP","Rio das Pedras"],	
        ["SP","Rio Grande da Serra"],	
        ["SP","Riolândia"],	
        ["SP","Riversul"],	
        ["SP","Rosana"],	
        ["SP","Roseira"],	
        ["SP","Rubiácea"],	
        ["SP","Rubinéia"],	
        ["SP","Sabino"],	
        ["SP","Sagres"],	
        ["SP","Sales"],	
        ["SP","Sales Oliveira"],	
        ["SP","Salesópolis"],	
        ["SP","Salmourão"],	
        ["SP","Saltinho"],	
        ["SP","Salto"],	
        ["SP","Salto de Pirapora"],	
        ["SP","Salto Grande"],	
        ["SP","Sandovalina"],	
        ["SP","Santa Adélia"],	
        ["SP","Santa Albertina"],	
        ["SP","Santa Bárbara d'Oeste"],	
        ["SP","Santa Branca"],	
        ["SP","Santa Clara d'Oeste"],	
        ["SP","Santa Cruz da Conceição"],	
        ["SP","Santa Cruz da Esperança"],	
        ["SP","Santa Cruz das Palmeiras"],	
        ["SP","Santa Cruz do Rio Pardo"],	
        ["SP","Santa Ernestina"],	
        ["SP","Santa Fé do Sul"],	
        ["SP","Santa Gertrudes"],	
        ["SP","Santa Isabel"],	
        ["SP","Santa Lúcia"],	
        ["SP","Santa Maria da Serra"],	
        ["SP","Santa Mercedes"],	
        ["SP","Santa Rita d'Oeste"],	
        ["SP","Santa Rita do Passa Quatro"],	
        ["SP","Santa Rosa de Viterbo"],	
        ["SP","Santa Salete"],	
        ["SP","Santana da Ponte Pensa"],	
        ["SP","Santana de Parnaíba"],	
        ["SP","Santo Anastácio"],	
        ["SP","Santo André"],	
        ["SP","Santo Antônio da Alegria"],	
        ["SP","Santo Antônio de Posse"],	
        ["SP","Santo Antônio do Aracanguá"],	
        ["SP","Santo Antônio do Jardim"],	
        ["SP","Santo Antônio do Pinhal"],	
        ["SP","Santo Expedito"],	
        ["SP","Santópolis do Aguapeí"],	
        ["SP","Santos"],	
        ["SP","São Bento do Sapucaí"],	
        ["SP","São Bernardo do Campo"],	
        ["SP","São Caetano do Sul"],	
        ["SP","São Carlos"],	
        ["SP","São Francisco"],	
        ["SP","São João da Boa Vista"],	
        ["SP","São João das Duas Pontes"],	
        ["SP","São João de Iracema"],	
        ["SP","São João do Pau-d'Alho"],	
        ["SP","São Joaquim da Barra"],	
        ["SP","São José da Bela Vista"],	
        ["SP","São José do Barreiro"],	
        ["SP","São José do Rio Pardo"],	
        ["SP","São José do Rio Preto"],	
        ["SP","São José dos Campos"],	
        ["SP","São Lourenço da Serra"],	
        ["SP","São Luiz do Paraitinga"],	
        ["SP","São Manuel"],	
        ["SP","São Miguel Arcanjo"],	
        ["SP","São Paulo"],	
        ["SP","São Pedro"],	
        ["SP","São Pedro do Turvo"],	
        ["SP","São Roque"],	
        ["SP","São Sebastião"],	
        ["SP","São Sebastião da Grama"],	
        ["SP","São Simão"],	
        ["SP","São Vicente"],	
        ["SP","Sarapuí"],	
        ["SP","Sarutaiá"],	
        ["SP","Sebastianópolis do Sul"],	
        ["SP","Serra Azul"],	
        ["SP","Serra Negra"],	
        ["SP","Serrana"],	
        ["SP","Sertãozinho"],	
        ["SP","Sete Barras"],	
        ["SP","Severínia"],	
        ["SP","Silveiras"],	
        ["SP","Socorro"],	
        ["SP","Sorocaba"],	
        ["SP","Sud Mennucci"],	
        ["SP","Sumaré"],	
        ["SP","Suzanápolis"],	
        ["SP","Suzano"],	
        ["SP","Tabapuã"],	
        ["SP","Tabatinga"],	
        ["SP","Taboão da Serra"],	
        ["SP","Taciba"],	
        ["SP","Taguaí"],	
        ["SP","Taiaçu"],	
        ["SP","Taiúva"],	
        ["SP","Tambaú"],	
        ["SP","Tanabi"],	
        ["SP","Tapiraí"],	
        ["SP","Tapiratiba"],	
        ["SP","Taquaral"],	
        ["SP","Taquaritinga"],	
        ["SP","Taquarituba"],	
        ["SP","Taquarivaí"],	
        ["SP","Tarabai"],	
        ["SP","Tarumã"],	
        ["SP","Tatuí"],	
        ["SP","Taubaté"],	
        ["SP","Tejupá"],	
        ["SP","Teodoro Sampaio"],	
        ["SP","Terra Roxa"],	
        ["SP","Tietê"],	
        ["SP","Timburi"],	
        ["SP","Torre de Pedra"],	
        ["SP","Torrinha"],	
        ["SP","Trabiju"],	
        ["SP","Tremembé"],	
        ["SP","Três Fronteiras"],	
        ["SP","Tuiuti"],	
        ["SP","Tupã"],	
        ["SP","Tupi Paulista"],	
        ["SP","Turiúba"],	
        ["SP","Turmalina"],	
        ["SP","Ubarana"],	
        ["SP","Ubatuba"],	
        ["SP","Ubirajara"],	
        ["SP","Uchoa"],	
        ["SP","União Paulista"],	
        ["SP","Urânia"],	
        ["SP","Uru"],	
        ["SP","Urupês"],	
        ["SP","Valentim Gentil"],	
        ["SP","Valinhos"],	
        ["SP","Valparaíso"],	
        ["SP","Vargem"],	
        ["SP","Vargem Grande do Sul"],	
        ["SP","Vargem Grande Paulista"],	
        ["SP","Várzea Paulista"],	
        ["SP","Vera Cruz"],	
        ["SP","Vinhedo"],	
        ["SP","Viradouro"],	
        ["SP","Vista Alegre do Alto"],	
        ["SP","Vitória Brasil"],	
        ["SP","Votorantim"],	
        ["SP","Votuporanga"],	
        ["SP","Zacarias"],	
        ["ES","Afonso Cláudio"],	
        ["ES","Água Doce do Norte"],	
        ["ES","Águia Branca"],	
        ["ES","Alegre"],	
        ["ES","Alfredo Chaves"],	
        ["ES","Alto Rio Novo"],	
        ["ES","Anchieta"],	
        ["ES","Apiacá"],	
        ["ES","Aracruz"],	
        ["ES","Atílio Vivácqua"],	
        ["ES","Baixo Guandu"],	
        ["ES","Barra de São Francisco"],	
        ["ES","Boa Esperança"],	
        ["ES","Bom Jesus do Norte"],	
        ["ES","Brejetuba"],	
        ["ES","Cachoeiro de Itapemirim"],	
        ["ES","Cariacica"],	
        ["ES","Castelo"],	
        ["ES","Colatina"],	
        ["ES","Conceição da Barra"],	
        ["ES","Conceição do Castelo"],	
        ["ES","Divino de São Lourenço"],	
        ["ES","Domingos Martins"],	
        ["ES","Dores do Rio Preto"],	
        ["ES","Ecoporanga"],	
        ["ES","Fundão"],	
        ["ES","Guaçuí"],	
        ["ES","Guarapari"],	
        ["ES","Ibatiba"],	
        ["ES","Ibiraçu"],	
        ["ES","Ibitirama"],	
        ["ES","Iconha"],	
        ["ES","Irupi"],	
        ["ES","Itaguaçu"],	
        ["ES","Itapemirim"],	
        ["ES","Itarana"],	
        ["ES","Iúna"],	
        ["ES","Jaguaré"],	
        ["ES","Jerônimo Monteiro"],	
        ["ES","João Neiva"],	
        ["ES","Laranja da Terra"],	
        ["ES","Linhares"],	
        ["ES","Mantenópolis"],	
        ["ES","Marataízes"],	
        ["ES","Marechal Floriano"],	
        ["ES","Marilândia"],	
        ["ES","Mimoso do Sul"],	
        ["ES","Montanha"],	
        ["ES","Mucurici"],	
        ["ES","Muniz Freire"],	
        ["ES","Muqui"],	
        ["ES","Nova Venécia"],	
        ["ES","Pancas"],	
        ["ES","Pedro Canário"],	
        ["ES","Pinheiros"],	
        ["ES","Piúma"],	
        ["ES","Ponto Belo"],	
        ["ES","Presidente Kennedy"],	
        ["ES","Rio Bananal"],	
        ["ES","Rio Novo do Sul"],	
        ["ES","Santa Leopoldina"],	
        ["ES","Santa Maria de Jetibá"],	
        ["ES","Santa Teresa"],	
        ["ES","São Domingos do Norte"],	
        ["ES","São Gabriel da Palha"],	
        ["ES","São José do Calçado"],	
        ["ES","São Mateus"],	
        ["ES","São Roque do Canaã"],	
        ["ES","Serra"],	
        ["ES","Sooretama"],	
        ["ES","Vargem Alta"],	
        ["ES","Venda Nova do Imigrante"],	
        ["ES","Viana"],	
        ["ES","Vila Pavão"],	
        ["ES","Vila Valério"],	
        ["ES","Vila Velha"],	
        ["ES","Vitória"],	
    ]


    var quais_opt_municipio = []
    var estado_escolhido = x.value


    municipios_por_estado.forEach((item, index) => {
        if(item[0] == estado_escolhido){
            quais_opt_municipio.push(item[1])
        }
    })

    //apaga para não ficar nada na memória
    document.getElementById("municipio").innerHTML = ''


    quais_opt_municipio.forEach((item, index) =>{
        document.getElementById("municipio").innerHTML += `
        <option> ` + item + `</option>
        `
    })
    console.log(quais_opt_municipio)
}

//funções para ver se os campos funcionam
function getMunicipio(){
    var recebeMunicipio = document.getElementById("municipio").value
    console.log(recebeMunicipio)
    
}


function getFaixaEtaria(){
    var recebeFaixa = document.getElementById("faixaetaria").value
    console.log(recebeFaixa)
}

function getAbordagem(){
    var recebeAbordagem = document.getElementById("abordagem").value
    console.log(recebeAbordagem)
}

function getProntoAtendimento(){
const recebeProntoAtendimento = document.getElementsByName("prontoatendimento")
recebeProntoAtendimento.forEach(prontoatendimento =>{
    prontoatendimento.addEventListener('click', ()=>{
        console.log(prontoatendimento.value)
    })  
})
}

//Enviar o formulário
let myForm = document.getElementById('myform')

//pega elementos
let estado = document.getElementById("estado")
let municipio = document.getElementById("municipio")
let faixa = document.getElementById("faixaetaria")
let abordagem = document.getElementById("abordagem")
let pa = document.querySelector('input[name="prontoatendimento"]:checked')

//tags de erro para campo vazio
let estado_error = document.getElementById("estado_error")
let municipio_error = document.getElementById("municipio_error")
let abordagem_error = document.getElementById("abordagem_error")
let faixaetaria_error = document.getElementById("faixaetaria_error")
let pa_error = document.getElementById("pa_error")


myForm.addEventListener('submit', async (e) =>{
    
    //Mensagens de erro para campo vazio


    if(estado.value === 'selecione' || estado.value === null)
    
    {
        e.preventDefault()
        estado_error.innerHTML = 'Preencha o campo'
    }
    else{
        estado_error.innerHTML = ''
    }

    if(municipio.value === '' || municipio.value === null)
    {
        e.preventDefault()
        municipio_error.innerHTML = 'Preencha este campo'
    }
    else{
        municipio_error.innerHTML = ''
    }

    if(faixa.value === 'selecione' || faixa.value === null)
    {
        e.preventDefault()
        faixaetaria_error.innerHTML = 'Preencha este campo'
    }
    else{
        faixaetaria_error.innerHTML = ''
    }

    if(abordagem.value === 'selecione' || abordagem.value === null)
    {
        e.preventDefault()
       abordagem_error.innerHTML = 'Preencha este campo'
    }
    else{
        abordagem_error.innerHTML = ''
    }

    //Redeclarar pa, se não o else nunca funcionaria, estaria sempre null
    let pa = document.querySelector('input[name="prontoatendimento"]:checked')

    if(!pa)
    {
        e.preventDefault()
       pa_error.innerHTML = 'Preencha este campo'
    }
    else{
        pa_error.innerHTML = ''
    }


    //Depois de preenchida, prevenir atualização da página
    e.preventDefault()
    console.log("SUBMITTED")

    //Pegamos os valores para filtrar e retornar a lista de instituições
    const filtros = {
        estado: estado.value,
        municipio: municipio.value,
        faixaetaria: faixa.value,
        abordagem: abordagem.value,
        prontoatendimento: pa.value
    }
    
    const resposta = await fetch("http://localhost:3000/api/instituicoes/filtrar", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(filtros)
    })
    const dados = await resposta.json()

    exibirResultados(dados)

})


//Exibir no front-end

function exibirResultados(lista){
    //passa a lista para o front-end
    const container = document.getElementById("resultado-container")
    container.innerHTML = ""
    //resposta com o css ajustado
    if(lista.length === 0){
        container.innerHTML = `
        <div style="
             background: var(--card);
                border: 1.5px solid var(--border);
                padding: 20px;
                border-radius: 12px;
                text-align: center;
                font-size: 18px;
                font-weight: 500;"> Nenhuma instituição encontrada. </div>
        `
        return
    }

    lista.forEach(item=>{
        container.innerHTML +=`
            <div class="resultado-card" style="
                background: var(--card);
                border: 1.5px solid var(--border);
                border-radius: 12px;
                padding: 22px;
                display: grid;
                gap: 8px;
                font-size: 17px;
                line-height: 1.4;
            ">
                <h3 style="
                    margin: 0 0 10px 0;
                    font-size: 22px;
                    font-weight: 600;
                    color: var(--text);
                "> ${item.nome}</h3>

                <p><strong>Estado:</strong> ${item.estado}</p>
                <p><strong>Município</strong> ${item.municipio}</p>
                <p><strong>Faixa etária:</strong> ${item.faixaetaria}</p>
                <p><strong>Abordagem:</strong> ${item.abordagem}</p>
                <p><strong>Pronto Atendimento:</strong> ${item.prontoatendimento}</p>
                ${item.telefone ? `<p><strong>Telefone:</strong> ${item.telefone}</p>` : ""}
                ${item.endereco ? `<p><strong>Endereço:</strong> ${item.endereco}</p>` : ""}
            </div>
        `
    })
}

